using NWN;

namespace NWM.API.Constants
{
  public enum TileSourceLightColor
  {
    Black = NWScript.TILE_SOURCE_LIGHT_COLOR_BLACK,
    White = NWScript.TILE_SOURCE_LIGHT_COLOR_WHITE,
    PaleDarkYellow = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_YELLOW,
    PaleYellow = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_YELLOW,
    PaleDarkGreen = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_GREEN,
    PaleGreen = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_GREEN,
    PaleDarkAqua = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_AQUA,
    PaleAqua = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_AQUA,
    PaleDarkBlue = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_BLUE,
    PaleBlue = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_BLUE,
    PaleDarkPurple = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_PURPLE,
    PalePurple = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_PURPLE,
    PaleDarkRed = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_RED,
    PaleRed = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_RED,
    PaleDarkOrange = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_DARK_ORANGE,
    PaleOrange = NWScript.TILE_SOURCE_LIGHT_COLOR_PALE_ORANGE
  }
}