using NWN.Core;

namespace NWN.API.Constants
{
  public enum AssociateCommand
  {
    StandGround = NWScript.ASSOCIATE_COMMAND_STANDGROUND,
    AttackNearest = NWScript.ASSOCIATE_COMMAND_ATTACKNEAREST,
    HealMaster = NWScript.ASSOCIATE_COMMAND_HEALMASTER,
    FollowMaster = NWScript.ASSOCIATE_COMMAND_FOLLOWMASTER,
    MasterFailedLockPick = NWScript.ASSOCIATE_COMMAND_MASTERFAILEDLOCKPICK,
    GuardMaster = NWScript.ASSOCIATE_COMMAND_GUARDMASTER,
    UnsummonFamiliar = NWScript.ASSOCIATE_COMMAND_UNSUMMONFAMILIAR,
    UnsummonAnimalCompanion = NWScript.ASSOCIATE_COMMAND_UNSUMMONANIMALCOMPANION,
    UnsummonSummoned = NWScript.ASSOCIATE_COMMAND_UNSUMMONSUMMONED,
    MasterUnderAttack = NWScript.ASSOCIATE_COMMAND_MASTERUNDERATTACK,
    ReleaseDomination = NWScript.ASSOCIATE_COMMAND_RELEASEDOMINATION,
    UnpossessFamiliar = NWScript.ASSOCIATE_COMMAND_UNPOSSESSFAMILIAR,
    MasterSawTrap = NWScript.ASSOCIATE_COMMAND_MASTERSAWTRAP,
    MasterAttackedOther = NWScript.ASSOCIATE_COMMAND_MASTERATTACKEDOTHER,
    MasterGoingToBeAttacked = NWScript.ASSOCIATE_COMMAND_MASTERGOINGTOBEATTACKED,
    LeaveParty = NWScript.ASSOCIATE_COMMAND_LEAVEPARTY,
    PickLock = NWScript.ASSOCIATE_COMMAND_PICKLOCK,
    Inventory = NWScript.ASSOCIATE_COMMAND_INVENTORY,
    DisarmTrap = NWScript.ASSOCIATE_COMMAND_DISARMTRAP,
    ToggleCasting = NWScript.ASSOCIATE_COMMAND_TOGGLECASTING,
    ToggleStealth = NWScript.ASSOCIATE_COMMAND_TOGGLESTEALTH,
    ToggleSearch = NWScript.ASSOCIATE_COMMAND_TOGGLESEARCH
  }
}
