using NWN.Core;

namespace NWN.API.Constants
{
  public enum DamagePower
  {
    Normal = NWScript.DAMAGE_POWER_NORMAL,
    Plus1 = NWScript.DAMAGE_POWER_PLUS_ONE,
    Plus2 = NWScript.DAMAGE_POWER_PLUS_TWO,
    Plus3 = NWScript.DAMAGE_POWER_PLUS_THREE,
    Plus4 = NWScript.DAMAGE_POWER_PLUS_FOUR,
    Plus5 = NWScript.DAMAGE_POWER_PLUS_FIVE,
    Plus6 = NWScript.DAMAGE_POWER_PLUS_SIX,
    Plus7 = NWScript.DAMAGE_POWER_PLUS_SEVEN,
    Plus8 = NWScript.DAMAGE_POWER_PLUS_EIGHT,
    Plus9 = NWScript.DAMAGE_POWER_PLUS_NINE,
    Plus10 = NWScript.DAMAGE_POWER_PLUS_TEN,
    Plus11 = NWScript.DAMAGE_POWER_PLUS_ELEVEN,
    Plus12 = NWScript.DAMAGE_POWER_PLUS_TWELVE,
    Plus13 = NWScript.DAMAGE_POWER_PLUS_THIRTEEN,
    Plus14 = NWScript.DAMAGE_POWER_PLUS_FOURTEEN,
    Plus15 = NWScript.DAMAGE_POWER_PLUS_FIFTEEN,
    Plus16 = NWScript.DAMAGE_POWER_PLUS_SIXTEEN,
    Plus17 = NWScript.DAMAGE_POWER_PLUS_SEVENTEEN,
    Plus18 = NWScript.DAMAGE_POWER_PLUS_EIGHTEEN,
    Plus19 = NWScript.DAMAGE_POWER_PLUS_NINTEEN,
    Plus20 = NWScript.DAMAGE_POWER_PLUS_TWENTY,
    Energy = NWScript.DAMAGE_POWER_ENERGY,
  }
}
