using NWN.Core;

namespace NWN.API.Constants
{
  public enum TileMainLightColor
  {
    Black = NWScript.TILE_MAIN_LIGHT_COLOR_BLACK,
    DimWhite = NWScript.TILE_MAIN_LIGHT_COLOR_DIM_WHITE,
    White = NWScript.TILE_MAIN_LIGHT_COLOR_WHITE,
    BrightWhite = NWScript.TILE_MAIN_LIGHT_COLOR_BRIGHT_WHITE,
    PaleDarkYellow = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_YELLOW,
    DarkYellow = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_YELLOW,
    PaleYellow = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_YELLOW,
    Yellow = NWScript.TILE_MAIN_LIGHT_COLOR_YELLOW,
    PaleDarkGreen = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_GREEN,
    DarkGreen = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_GREEN,
    PaleGreen = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_GREEN,
    Green = NWScript.TILE_MAIN_LIGHT_COLOR_GREEN,
    PaleDarkAqua = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_AQUA,
    DarkAqua = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_AQUA,
    PaleAqua = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_AQUA,
    Aqua = NWScript.TILE_MAIN_LIGHT_COLOR_AQUA,
    PaleDarkBlue = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_BLUE,
    DarkBlue = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_BLUE,
    PaleBlue = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_BLUE,
    Blue = NWScript.TILE_MAIN_LIGHT_COLOR_BLUE,
    PaleDarkPurple = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_PURPLE,
    DarkPurple = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_PURPLE,
    PalePurple = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_PURPLE,
    Purple = NWScript.TILE_MAIN_LIGHT_COLOR_PURPLE,
    PaleDarkRed = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_RED,
    DarkRed = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_RED,
    PaleRed = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_RED,
    Red = NWScript.TILE_MAIN_LIGHT_COLOR_RED,
    PaleDarkOrange = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_DARK_ORANGE,
    DarkOrange = NWScript.TILE_MAIN_LIGHT_COLOR_DARK_ORANGE,
    PaleOrange = NWScript.TILE_MAIN_LIGHT_COLOR_PALE_ORANGE,
    Orange = NWScript.TILE_MAIN_LIGHT_COLOR_ORANGE
  }
}