var namespaceNWNX_1_1API =
[
    [ "Events", "namespaceNWNX_1_1API_1_1Events.html", "namespaceNWNX_1_1API_1_1Events" ],
    [ "Administration", "classNWNX_1_1API_1_1Administration.html", "classNWNX_1_1API_1_1Administration" ],
    [ "Appearance", "classNWNX_1_1API_1_1Appearance.html", null ],
    [ "Area", "classNWNX_1_1API_1_1Area.html", null ],
    [ "Chat", "classNWNX_1_1API_1_1Chat.html", null ],
    [ "Creature", "classNWNX_1_1API_1_1Creature.html", "classNWNX_1_1API_1_1Creature" ],
    [ "Damage", "classNWNX_1_1API_1_1Damage.html", null ],
    [ "Dialog", "classNWNX_1_1API_1_1Dialog.html", "classNWNX_1_1API_1_1Dialog" ],
    [ "Effect", "classNWNX_1_1API_1_1Effect.html", null ],
    [ "ELC", "classNWNX_1_1API_1_1ELC.html", null ],
    [ "Encounter", "classNWNX_1_1API_1_1Encounter.html", null ],
    [ "Feedback", "classNWNX_1_1API_1_1Feedback.html", null ],
    [ "Item", "classNWNX_1_1API_1_1Item.html", null ],
    [ "ItemProperty", "classNWNX_1_1API_1_1ItemProperty.html", null ],
    [ "Object", "classNWNX_1_1API_1_1Object.html", "classNWNX_1_1API_1_1Object" ],
    [ "Player", "classNWNX_1_1API_1_1Player.html", "classNWNX_1_1API_1_1Player" ],
    [ "QuickBarSlot", "structNWNX_1_1API_1_1QuickBarSlot.html", "structNWNX_1_1API_1_1QuickBarSlot" ],
    [ "Rename", "classNWNX_1_1API_1_1Rename.html", null ],
    [ "Reveal", "classNWNX_1_1API_1_1Reveal.html", null ],
    [ "SkillRanks", "classNWNX_1_1API_1_1SkillRanks.html", null ],
    [ "Util", "classNWNX_1_1API_1_1Util.html", "classNWNX_1_1API_1_1Util" ],
    [ "Visibility", "classNWNX_1_1API_1_1Visibility.html", null ],
    [ "Weapon", "classNWNX_1_1API_1_1Weapon.html", null ]
];