var searchData=
[
  ['api_451',['API',['../namespaceNWN_1_1API.html',1,'NWN.API'],['../namespaceNWNX_1_1API.html',1,'NWNX.API']]],
  ['constants_452',['Constants',['../namespaceNWN_1_1API_1_1Constants.html',1,'NWN.API.Constants'],['../namespaceNWNX_1_1API_1_1Constants.html',1,'NWNX.API.Constants']]],
  ['events_453',['Events',['../namespaceNWN_1_1API_1_1Events.html',1,'NWN.API.Events'],['../namespaceNWNX_1_1API_1_1Events.html',1,'NWNX.API.Events']]],
  ['nwn_2emanaged_454',['NWN.Managed',['../index.html',1,'']]],
  ['name_455',['Name',['../classNWN_1_1API_1_1NwObject.html#aa846acd023d4bb670627fc7e9ed00376',1,'NWN::API::NwObject']]],
  ['nativeevent_456',['NativeEvent',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN.API.Events.NativeEvent'],['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN.API.Events.NativeEvent&lt; TObject, TEvent &gt;']]],
  ['nativeevent_3c_20nwarea_2c_20onenter_20_3e_457',['NativeEvent&lt; NwArea, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwarea_2c_20onexit_20_3e_458',['NativeEvent&lt; NwArea, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwarea_2c_20onheartbeat_20_3e_459',['NativeEvent&lt; NwArea, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwarea_2c_20onuserdefined_20_3e_460',['NativeEvent&lt; NwArea, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onenter_20_3e_461',['NativeEvent&lt; NwAreaOfEffect, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onexit_20_3e_462',['NativeEvent&lt; NwAreaOfEffect, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onheartbeat_20_3e_463',['NativeEvent&lt; NwAreaOfEffect, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onuserdefined_20_3e_464',['NativeEvent&lt; NwAreaOfEffect, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onblocked_20_3e_465',['NativeEvent&lt; NwCreature, OnBlocked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20oncombatroundend_20_3e_466',['NativeEvent&lt; NwCreature, OnCombatRoundEnd &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onconversation_20_3e_467',['NativeEvent&lt; NwCreature, OnConversation &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20ondamaged_20_3e_468',['NativeEvent&lt; NwCreature, OnDamaged &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20ondeath_20_3e_469',['NativeEvent&lt; NwCreature, OnDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20ondisturbed_20_3e_470',['NativeEvent&lt; NwCreature, OnDisturbed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onheartbeat_20_3e_471',['NativeEvent&lt; NwCreature, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onperception_20_3e_472',['NativeEvent&lt; NwCreature, OnPerception &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onphysicalattacked_20_3e_473',['NativeEvent&lt; NwCreature, OnPhysicalAttacked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onrested_20_3e_474',['NativeEvent&lt; NwCreature, OnRested &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onspawn_20_3e_475',['NativeEvent&lt; NwCreature, OnSpawn &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onspellcastat_20_3e_476',['NativeEvent&lt; NwCreature, OnSpellCastAt &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onuserdefined_20_3e_477',['NativeEvent&lt; NwCreature, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onareatransitionclick_20_3e_478',['NativeEvent&lt; NwDoor, OnAreaTransitionClick &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onclose_20_3e_479',['NativeEvent&lt; NwDoor, OnClose &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondamaged_20_3e_480',['NativeEvent&lt; NwDoor, OnDamaged &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondeath_20_3e_481',['NativeEvent&lt; NwDoor, OnDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondialogue_20_3e_482',['NativeEvent&lt; NwDoor, OnDialogue &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondisarm_20_3e_483',['NativeEvent&lt; NwDoor, OnDisarm &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onfailtoopen_20_3e_484',['NativeEvent&lt; NwDoor, OnFailToOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onheartbeat_20_3e_485',['NativeEvent&lt; NwDoor, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onlock_20_3e_486',['NativeEvent&lt; NwDoor, OnLock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onopen_20_3e_487',['NativeEvent&lt; NwDoor, OnOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onphysicalattacked_20_3e_488',['NativeEvent&lt; NwDoor, OnPhysicalAttacked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onspellcastat_20_3e_489',['NativeEvent&lt; NwDoor, OnSpellCastAt &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ontraptriggered_20_3e_490',['NativeEvent&lt; NwDoor, OnTrapTriggered &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onunlock_20_3e_491',['NativeEvent&lt; NwDoor, OnUnlock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onuserdefined_20_3e_492',['NativeEvent&lt; NwDoor, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onenter_20_3e_493',['NativeEvent&lt; NwEncounter, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onexhausted_20_3e_494',['NativeEvent&lt; NwEncounter, OnExhausted &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onexit_20_3e_495',['NativeEvent&lt; NwEncounter, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onheartbeat_20_3e_496',['NativeEvent&lt; NwEncounter, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onuserdefined_20_3e_497',['NativeEvent&lt; NwEncounter, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onacquireitem_20_3e_498',['NativeEvent&lt; NwModule, OnAcquireItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onactivateitem_20_3e_499',['NativeEvent&lt; NwModule, OnActivateItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20oncliententer_20_3e_500',['NativeEvent&lt; NwModule, OnClientEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onclientleave_20_3e_501',['NativeEvent&lt; NwModule, OnClientLeave &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20oncutsceneabort_20_3e_502',['NativeEvent&lt; NwModule, OnCutsceneAbort &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onheartbeat_20_3e_503',['NativeEvent&lt; NwModule, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onmoduleload_20_3e_504',['NativeEvent&lt; NwModule, OnModuleLoad &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onmodulestart_20_3e_505',['NativeEvent&lt; NwModule, OnModuleStart &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerchat_20_3e_506',['NativeEvent&lt; NwModule, OnPlayerChat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerdeath_20_3e_507',['NativeEvent&lt; NwModule, OnPlayerDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerdying_20_3e_508',['NativeEvent&lt; NwModule, OnPlayerDying &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerequipitem_20_3e_509',['NativeEvent&lt; NwModule, OnPlayerEquipItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerlevelup_20_3e_510',['NativeEvent&lt; NwModule, OnPlayerLevelUp &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerrespawn_20_3e_511',['NativeEvent&lt; NwModule, OnPlayerRespawn &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerrest_20_3e_512',['NativeEvent&lt; NwModule, OnPlayerRest &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayertarget_20_3e_513',['NativeEvent&lt; NwModule, OnPlayerTarget &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerunequipitem_20_3e_514',['NativeEvent&lt; NwModule, OnPlayerUnequipItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onunacquireitem_20_3e_515',['NativeEvent&lt; NwModule, OnUnacquireItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onuserdefined_20_3e_516',['NativeEvent&lt; NwModule, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onclose_20_3e_517',['NativeEvent&lt; NwPlaceable, OnClose &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondamaged_20_3e_518',['NativeEvent&lt; NwPlaceable, OnDamaged &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondeath_20_3e_519',['NativeEvent&lt; NwPlaceable, OnDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondialogue_20_3e_520',['NativeEvent&lt; NwPlaceable, OnDialogue &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondisarm_20_3e_521',['NativeEvent&lt; NwPlaceable, OnDisarm &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondisturbed_20_3e_522',['NativeEvent&lt; NwPlaceable, OnDisturbed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onheartbeat_20_3e_523',['NativeEvent&lt; NwPlaceable, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onleftclick_20_3e_524',['NativeEvent&lt; NwPlaceable, OnLeftClick &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onlock_20_3e_525',['NativeEvent&lt; NwPlaceable, OnLock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onopen_20_3e_526',['NativeEvent&lt; NwPlaceable, OnOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onphysicalattacked_20_3e_527',['NativeEvent&lt; NwPlaceable, OnPhysicalAttacked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onspellcastat_20_3e_528',['NativeEvent&lt; NwPlaceable, OnSpellCastAt &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ontraptriggered_20_3e_529',['NativeEvent&lt; NwPlaceable, OnTrapTriggered &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onunlock_20_3e_530',['NativeEvent&lt; NwPlaceable, OnUnlock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onused_20_3e_531',['NativeEvent&lt; NwPlaceable, OnUsed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onuserdefined_20_3e_532',['NativeEvent&lt; NwPlaceable, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwstore_2c_20onclose_20_3e_533',['NativeEvent&lt; NwStore, OnClose &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwstore_2c_20onopen_20_3e_534',['NativeEvent&lt; NwStore, OnOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onclicked_20_3e_535',['NativeEvent&lt; NwTrigger, OnClicked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20ondisarmed_20_3e_536',['NativeEvent&lt; NwTrigger, OnDisarmed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onenter_20_3e_537',['NativeEvent&lt; NwTrigger, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onexit_20_3e_538',['NativeEvent&lt; NwTrigger, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onheartbeat_20_3e_539',['NativeEvent&lt; NwTrigger, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20ontraptriggered_20_3e_540',['NativeEvent&lt; NwTrigger, OnTrapTriggered &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onuserdefined_20_3e_541',['NativeEvent&lt; NwTrigger, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeeventattribute_542',['NativeEventAttribute',['../classNWN_1_1API_1_1Events_1_1NativeEventAttribute.html',1,'NWN::API::Events']]],
  ['nativeeventservice_543',['NativeEventService',['../classNWN_1_1Services_1_1NativeEventService.html',1,'NWN::Services']]],
  ['nativescript_544',['NativeScript',['../classNWN_1_1API_1_1NativeScript.html',1,'NWN::API']]],
  ['newleader_545',['NewLeader',['../classNWNX_1_1API_1_1Events_1_1PartyEvents_1_1OnTransferLeadershipBefore.html#a6578f2be0fea5218636735fe87a43473',1,'NWNX.API.Events.PartyEvents.OnTransferLeadershipBefore.NewLeader()'],['../classNWNX_1_1API_1_1Events_1_1PartyEvents_1_1OnTransferLeadershipAfter.html#a0b8d7f113ccbc3c6ba71dfd2193885ce',1,'NWNX.API.Events.PartyEvents.OnTransferLeadershipAfter.NewLeader()']]],
  ['newreputation_546',['NewReputation',['../classNWNX_1_1API_1_1Events_1_1FactionEvents_1_1OnSetNPCFactionReputationBefore.html#a7de33cf9cddc1b8f767d227d2bc75e6c',1,'NWNX.API.Events.FactionEvents.OnSetNPCFactionReputationBefore.NewReputation()'],['../classNWNX_1_1API_1_1Events_1_1FactionEvents_1_1OnSetNPCFactionReputationAfter.html#ac20ecfe0e2751f51908f69651c1c8de6',1,'NWNX.API.Events.FactionEvents.OnSetNPCFactionReputationAfter.NewReputation()']]],
  ['newtomodule_547',['NewToModule',['../classNWNX_1_1API_1_1Events_1_1ServerSendAreaEvents_1_1OnServerSendAreaBefore.html#a978dd1d8faff96683afcdbf268e4a8a8',1,'NWNX.API.Events.ServerSendAreaEvents.OnServerSendAreaBefore.NewToModule()'],['../classNWNX_1_1API_1_1Events_1_1ServerSendAreaEvents_1_1OnServerSendAreaAfter.html#ac51fbd07b5a364197643d4f81123ae35',1,'NWNX.API.Events.ServerSendAreaEvents.OnServerSendAreaAfter.NewToModule()']]],
  ['nextdouble_548',['NextDouble',['../classNWN_1_1API_1_1RandomExtensions.html#ad8dd4f09c4629e8a34ab4111052c2307',1,'NWN::API::RandomExtensions']]],
  ['nextfloat_549',['NextFloat',['../classNWN_1_1API_1_1RandomExtensions.html#ae56c7315f39fb225ab4c402c991a4c68',1,'NWN.API.RandomExtensions.NextFloat(this Random random)'],['../classNWN_1_1API_1_1RandomExtensions.html#a30a99195dac7180c94ae1edacdc36f4a',1,'NWN.API.RandomExtensions.NextFloat(this Random random, float minValue, float maxValue)']]],
  ['nextframe_550',['NextFrame',['../classNWN_1_1API_1_1NwTask.html#a9f4e6db66a44b051a6f98b76dbd88fb4',1,'NWN::API::NwTask']]],
  ['nighttoday_551',['NightToDay',['../classNWN_1_1API_1_1NwPlayer.html#a21fefcbd1d72624b17bb6ff526eb49f5',1,'NWN::API::NwPlayer']]],
  ['nmanager_552',['NManager',['../classNWN_1_1NManager.html',1,'NWN']]],
  ['now_553',['Now',['../structNWN_1_1Services_1_1NwDateTime.html#a3dc311a7f156ddbb90f9a916dc38915a',1,'NWN::Services::NwDateTime']]],
  ['nwarea_554',['NwArea',['../classNWN_1_1API_1_1NwArea.html',1,'NWN::API']]],
  ['nwareaofeffect_555',['NwAreaOfEffect',['../classNWN_1_1API_1_1NwAreaOfEffect.html',1,'NWN::API']]],
  ['nwcreature_556',['NwCreature',['../classNWN_1_1API_1_1NwCreature.html',1,'NWN::API']]],
  ['nwdatetime_557',['NwDateTime',['../structNWN_1_1Services_1_1NwDateTime.html',1,'NWN::Services']]],
  ['nwdoor_558',['NwDoor',['../classNWN_1_1API_1_1NwDoor.html',1,'NWN::API']]],
  ['nwencounter_559',['NwEncounter',['../classNWN_1_1API_1_1NwEncounter.html',1,'NWN::API']]],
  ['nwfaction_560',['NwFaction',['../classNWN_1_1API_1_1NwFaction.html',1,'NWN::API']]],
  ['nwgameobject_561',['NwGameObject',['../classNWN_1_1API_1_1NwGameObject.html',1,'NWN::API']]],
  ['nwitem_562',['NwItem',['../classNWN_1_1API_1_1NwItem.html',1,'NWN::API']]],
  ['nwmath_563',['NwMath',['../classNWN_1_1API_1_1NwMath.html',1,'NWN::API']]],
  ['nwmodule_564',['NwModule',['../classNWN_1_1API_1_1NwModule.html',1,'NWN::API']]],
  ['nwn_565',['NWN',['../namespaceNWN.html',1,'']]],
  ['nwnx_566',['NWNX',['../namespaceNWNX.html',1,'']]],
  ['nwnxattackeventattribute_567',['NWNXAttackEventAttribute',['../classNWNX_1_1API_1_1Events_1_1NWNXAttackEventAttribute.html',1,'NWNX::API::Events']]],
  ['nwnxdamageeventattribute_568',['NWNXDamageEventAttribute',['../classNWNX_1_1API_1_1Events_1_1NWNXDamageEventAttribute.html',1,'NWNX::API::Events']]],
  ['nwnxevent_569',['NWNXEvent',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX.API.Events.NWNXEvent'],['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX.API.Events.NWNXEvent&lt; T &gt;']]],
  ['nwnxevent_3c_20attackevent_20_3e_570',['NWNXEvent&lt; AttackEvent &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20damageevent_20_3e_571',['NWNXEvent&lt; DamageEvent &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onaddassociateafter_20_3e_572',['NWNXEvent&lt; OnAddAssociateAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onaddassociatebefore_20_3e_573',['NWNXEvent&lt; OnAddAssociateBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendardawn_20_3e_574',['NWNXEvent&lt; OnCalendarDawn &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendarday_20_3e_575',['NWNXEvent&lt; OnCalendarDay &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendardusk_20_3e_576',['NWNXEvent&lt; OnCalendarDusk &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendarhour_20_3e_577',['NWNXEvent&lt; OnCalendarHour &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendarmonth_20_3e_578',['NWNXEvent&lt; OnCalendarMonth &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendaryear_20_3e_579',['NWNXEvent&lt; OnCalendarYear &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onenterstealthafter_20_3e_580',['NWNXEvent&lt; OnEnterStealthAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onenterstealthbefore_20_3e_581',['NWNXEvent&lt; OnEnterStealthBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexamineobjectafter_20_3e_582',['NWNXEvent&lt; OnExamineObjectAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexamineobjectbefore_20_3e_583',['NWNXEvent&lt; OnExamineObjectBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexitstealthafter_20_3e_584',['NWNXEvent&lt; OnExitStealthAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexitstealthbefore_20_3e_585',['NWNXEvent&lt; OnExitStealthBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onremoveassociateafter_20_3e_586',['NWNXEvent&lt; OnRemoveAssociateAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onremoveassociatebefore_20_3e_587',['NWNXEvent&lt; OnRemoveAssociateBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onservercharactersaveafter_20_3e_588',['NWNXEvent&lt; OnServerCharacterSaveAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onserversendareaafter_20_3e_589',['NWNXEvent&lt; OnServerSendAreaAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onserversendareabefore_20_3e_590',['NWNXEvent&lt; OnServerSendAreaBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestbuyafter_20_3e_591',['NWNXEvent&lt; OnStoreRequestBuyAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestbuybefore_20_3e_592',['NWNXEvent&lt; OnStoreRequestBuyBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestsellafter_20_3e_593',['NWNXEvent&lt; OnStoreRequestSellAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestsellbefore_20_3e_594',['NWNXEvent&lt; OnStoreRequestSellBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onvalidateequipitemafter_20_3e_595',['NWNXEvent&lt; OnValidateEquipItemAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onvalidateuseitemafter_20_3e_596',['NWNXEvent&lt; OnValidateUseItemAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20t_20_3e_597',['NWNXEvent&lt; T &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxeventattribute_598',['NWNXEventAttribute',['../classNWNX_1_1API_1_1Events_1_1NWNXEventAttribute.html',1,'NWNX::API::Events']]],
  ['nwnxeventservice_599',['NWNXEventService',['../classNWNX_1_1Services_1_1NWNXEventService.html',1,'NWNX::Services']]],
  ['nwnxeventskippable_600',['NWNXEventSkippable',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onacceptinvitationafter_20_3e_601',['NWNXEventSkippable&lt; OnAcceptInvitationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onacceptinvitationbefore_20_3e_602',['NWNXEventSkippable&lt; OnAcceptInvitationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onbarterstartafter_20_3e_603',['NWNXEventSkippable&lt; OnBarterStartAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onbarterstartbefore_20_3e_604',['NWNXEventSkippable&lt; OnBarterStartBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientconnectafter_20_3e_605',['NWNXEventSkippable&lt; OnClientConnectAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientconnectbefore_20_3e_606',['NWNXEventSkippable&lt; OnClientConnectBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientdisconnectafter_20_3e_607',['NWNXEventSkippable&lt; OnClientDisconnectAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientdisconnectbefore_20_3e_608',['NWNXEventSkippable&lt; OnClientDisconnectBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onhealafter_20_3e_609',['NWNXEventSkippable&lt; OnHealAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onhealbefore_20_3e_610',['NWNXEventSkippable&lt; OnHealBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onignoreinvitationafter_20_3e_611',['NWNXEventSkippable&lt; OnIgnoreInvitationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onignoreinvitationbefore_20_3e_612',['NWNXEventSkippable&lt; OnIgnoreInvitationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryaddgoldafter_20_3e_613',['NWNXEventSkippable&lt; OnInventoryAddGoldAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryaddgoldbefore_20_3e_614',['NWNXEventSkippable&lt; OnInventoryAddGoldBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventorycloseafter_20_3e_615',['NWNXEventSkippable&lt; OnInventoryCloseAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryclosebefore_20_3e_616',['NWNXEventSkippable&lt; OnInventoryCloseBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryopenafter_20_3e_617',['NWNXEventSkippable&lt; OnInventoryOpenAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryopenbefore_20_3e_618',['NWNXEventSkippable&lt; OnInventoryOpenBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryremovegoldafter_20_3e_619',['NWNXEventSkippable&lt; OnInventoryRemoveGoldAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryremovegoldbefore_20_3e_620',['NWNXEventSkippable&lt; OnInventoryRemoveGoldBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninviteafter_20_3e_621',['NWNXEventSkippable&lt; OnInviteAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninvitebefore_20_3e_622',['NWNXEventSkippable&lt; OnInviteBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitemequipbefore_20_3e_623',['NWNXEventSkippable&lt; OnItemEquipBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitempaytoidentifyafter_20_3e_624',['NWNXEventSkippable&lt; OnItemPayToIdentifyAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitempaytoidentifybefore_20_3e_625',['NWNXEventSkippable&lt; OnItemPayToIdentifyBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitemusebefore_20_3e_626',['NWNXEventSkippable&lt; OnItemUseBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickafter_20_3e_627',['NWNXEventSkippable&lt; OnKickAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickbefore_20_3e_628',['NWNXEventSkippable&lt; OnKickBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickhenchmanafter_20_3e_629',['NWNXEventSkippable&lt; OnKickHenchmanAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickhenchmanbefore_20_3e_630',['NWNXEventSkippable&lt; OnKickHenchmanBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleaveafter_20_3e_631',['NWNXEventSkippable&lt; OnLeaveAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleavebefore_20_3e_632',['NWNXEventSkippable&lt; OnLeaveBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleveldownafter_20_3e_633',['NWNXEventSkippable&lt; OnLevelDownAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleveldownbefore_20_3e_634',['NWNXEventSkippable&lt; OnLevelDownBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupafter_20_3e_635',['NWNXEventSkippable&lt; OnLevelUpAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupautomaticafter_20_3e_636',['NWNXEventSkippable&lt; OnLevelUpAutomaticAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupautomaticbefore_20_3e_637',['NWNXEventSkippable&lt; OnLevelUpAutomaticBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupbefore_20_3e_638',['NWNXEventSkippable&lt; OnLevelUpBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onplayerdmloginafter_20_3e_639',['NWNXEventSkippable&lt; OnPlayerDMLoginAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onplayerdmloginbefore_20_3e_640',['NWNXEventSkippable&lt; OnPlayerDMLoginBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onplayerdmlogoutafter_20_3e_641',['NWNXEventSkippable&lt; OnPlayerDMLogoutAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onplayerdmlogoutbefore_20_3e_642',['NWNXEventSkippable&lt; OnPlayerDMLogoutBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onrejectinvitationafter_20_3e_643',['NWNXEventSkippable&lt; OnRejectInvitationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onrejectinvitationbefore_20_3e_644',['NWNXEventSkippable&lt; OnRejectInvitationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onresourceadded_20_3e_645',['NWNXEventSkippable&lt; OnResourceAdded &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onresourcemodified_20_3e_646',['NWNXEventSkippable&lt; OnResourceModified &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onresourceremoved_20_3e_647',['NWNXEventSkippable&lt; OnResourceRemoved &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onservercharactersavebefore_20_3e_648',['NWNXEventSkippable&lt; OnServerCharacterSaveBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onsetmemorizedspellslotbefore_20_3e_649',['NWNXEventSkippable&lt; OnSetMemorizedSpellSlotBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onsetnpcfactionreputationafter_20_3e_650',['NWNXEventSkippable&lt; OnSetNPCFactionReputationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onsetnpcfactionreputationbefore_20_3e_651',['NWNXEventSkippable&lt; OnSetNPCFactionReputationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20ontransferleadershipafter_20_3e_652',['NWNXEventSkippable&lt; OnTransferLeadershipAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20ontransferleadershipbefore_20_3e_653',['NWNXEventSkippable&lt; OnTransferLeadershipBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onusefeatbefore_20_3e_654',['NWNXEventSkippable&lt; OnUseFeatBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onvalidateafter_20_3e_655',['NWNXEventSkippable&lt; OnValidateAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onvalidatebefore_20_3e_656',['NWNXEventSkippable&lt; OnValidateBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwobject_657',['NwObject',['../classNWN_1_1API_1_1NwObject.html',1,'NWN::API']]],
  ['nwplaceable_658',['NwPlaceable',['../classNWN_1_1API_1_1NwPlaceable.html',1,'NWN::API']]],
  ['nwplayer_659',['NwPlayer',['../classNWN_1_1API_1_1NwPlayer.html',1,'NWN::API']]],
  ['nwrandom_660',['NwRandom',['../classNWN_1_1API_1_1NwRandom.html',1,'NWN::API']]],
  ['nwsound_661',['NwSound',['../classNWN_1_1API_1_1NwSound.html',1,'NWN::API']]],
  ['nwstationary_662',['NwStationary',['../classNWN_1_1API_1_1NwStationary.html',1,'NWN::API']]],
  ['nwstore_663',['NwStore',['../classNWN_1_1API_1_1NwStore.html',1,'NWN::API']]],
  ['nwtask_664',['NwTask',['../classNWN_1_1API_1_1NwTask.html',1,'NWN::API']]],
  ['nwtimespan_665',['NwTimeSpan',['../classNWN_1_1API_1_1NwTimeSpan.html',1,'NWN::API']]],
  ['nwtrappable_666',['NwTrappable',['../classNWN_1_1API_1_1NwTrappable.html',1,'NWN::API']]],
  ['nwtrigger_667',['NwTrigger',['../classNWN_1_1API_1_1NwTrigger.html',1,'NWN::API']]],
  ['nwwaypoint_668',['NwWaypoint',['../classNWN_1_1API_1_1NwWaypoint.html',1,'NWN::API']]],
  ['plugins_669',['Plugins',['../namespaceNWN_1_1Plugins.html',1,'NWN']]],
  ['services_670',['Services',['../namespaceNWN_1_1Services.html',1,'NWN.Services'],['../namespaceNWNX_1_1Services.html',1,'NWNX.Services']]]
];
