var searchData=
[
  ['api_438',['API',['../namespaceNWN_1_1API.html',1,'NWN.API'],['../namespaceNWNX_1_1API.html',1,'NWNX.API']]],
  ['constants_439',['Constants',['../namespaceNWN_1_1API_1_1Constants.html',1,'NWN.API.Constants'],['../namespaceNWNX_1_1API_1_1Constants.html',1,'NWNX.API.Constants']]],
  ['events_440',['Events',['../namespaceNWN_1_1API_1_1Events.html',1,'NWN.API.Events'],['../namespaceNWNX_1_1API_1_1Events.html',1,'NWNX.API.Events']]],
  ['nwn_2emanaged_441',['NWN.Managed',['../index.html',1,'']]],
  ['name_442',['Name',['../classNWN_1_1API_1_1NwObject.html#aa846acd023d4bb670627fc7e9ed00376',1,'NWN::API::NwObject']]],
  ['nativeevent_443',['NativeEvent',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN.API.Events.NativeEvent'],['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN.API.Events.NativeEvent&lt; TObject, TEvent &gt;']]],
  ['nativeevent_3c_20nwarea_2c_20onenter_20_3e_444',['NativeEvent&lt; NwArea, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwarea_2c_20onexit_20_3e_445',['NativeEvent&lt; NwArea, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwarea_2c_20onheartbeat_20_3e_446',['NativeEvent&lt; NwArea, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwarea_2c_20onuserdefined_20_3e_447',['NativeEvent&lt; NwArea, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onenter_20_3e_448',['NativeEvent&lt; NwAreaOfEffect, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onexit_20_3e_449',['NativeEvent&lt; NwAreaOfEffect, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onheartbeat_20_3e_450',['NativeEvent&lt; NwAreaOfEffect, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwareaofeffect_2c_20onuserdefined_20_3e_451',['NativeEvent&lt; NwAreaOfEffect, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onblocked_20_3e_452',['NativeEvent&lt; NwCreature, OnBlocked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20oncombatroundend_20_3e_453',['NativeEvent&lt; NwCreature, OnCombatRoundEnd &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onconversation_20_3e_454',['NativeEvent&lt; NwCreature, OnConversation &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20ondamaged_20_3e_455',['NativeEvent&lt; NwCreature, OnDamaged &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20ondeath_20_3e_456',['NativeEvent&lt; NwCreature, OnDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20ondisturbed_20_3e_457',['NativeEvent&lt; NwCreature, OnDisturbed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onheartbeat_20_3e_458',['NativeEvent&lt; NwCreature, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onperception_20_3e_459',['NativeEvent&lt; NwCreature, OnPerception &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onphysicalattacked_20_3e_460',['NativeEvent&lt; NwCreature, OnPhysicalAttacked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onrested_20_3e_461',['NativeEvent&lt; NwCreature, OnRested &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onspawn_20_3e_462',['NativeEvent&lt; NwCreature, OnSpawn &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onspellcastat_20_3e_463',['NativeEvent&lt; NwCreature, OnSpellCastAt &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwcreature_2c_20onuserdefined_20_3e_464',['NativeEvent&lt; NwCreature, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onareatransitionclick_20_3e_465',['NativeEvent&lt; NwDoor, OnAreaTransitionClick &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onclose_20_3e_466',['NativeEvent&lt; NwDoor, OnClose &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondamaged_20_3e_467',['NativeEvent&lt; NwDoor, OnDamaged &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondeath_20_3e_468',['NativeEvent&lt; NwDoor, OnDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondialogue_20_3e_469',['NativeEvent&lt; NwDoor, OnDialogue &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ondisarm_20_3e_470',['NativeEvent&lt; NwDoor, OnDisarm &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onfailtoopen_20_3e_471',['NativeEvent&lt; NwDoor, OnFailToOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onheartbeat_20_3e_472',['NativeEvent&lt; NwDoor, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onlock_20_3e_473',['NativeEvent&lt; NwDoor, OnLock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onopen_20_3e_474',['NativeEvent&lt; NwDoor, OnOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onphysicalattacked_20_3e_475',['NativeEvent&lt; NwDoor, OnPhysicalAttacked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onspellcastat_20_3e_476',['NativeEvent&lt; NwDoor, OnSpellCastAt &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20ontraptriggered_20_3e_477',['NativeEvent&lt; NwDoor, OnTrapTriggered &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onunlock_20_3e_478',['NativeEvent&lt; NwDoor, OnUnlock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwdoor_2c_20onuserdefined_20_3e_479',['NativeEvent&lt; NwDoor, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onenter_20_3e_480',['NativeEvent&lt; NwEncounter, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onexhausted_20_3e_481',['NativeEvent&lt; NwEncounter, OnExhausted &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onexit_20_3e_482',['NativeEvent&lt; NwEncounter, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onheartbeat_20_3e_483',['NativeEvent&lt; NwEncounter, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwencounter_2c_20onuserdefined_20_3e_484',['NativeEvent&lt; NwEncounter, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onacquireitem_20_3e_485',['NativeEvent&lt; NwModule, OnAcquireItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onactivateitem_20_3e_486',['NativeEvent&lt; NwModule, OnActivateItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20oncliententer_20_3e_487',['NativeEvent&lt; NwModule, OnClientEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onclientleave_20_3e_488',['NativeEvent&lt; NwModule, OnClientLeave &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20oncutsceneabort_20_3e_489',['NativeEvent&lt; NwModule, OnCutsceneAbort &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onheartbeat_20_3e_490',['NativeEvent&lt; NwModule, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onmoduleload_20_3e_491',['NativeEvent&lt; NwModule, OnModuleLoad &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onmodulestart_20_3e_492',['NativeEvent&lt; NwModule, OnModuleStart &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerchat_20_3e_493',['NativeEvent&lt; NwModule, OnPlayerChat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerdeath_20_3e_494',['NativeEvent&lt; NwModule, OnPlayerDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerdying_20_3e_495',['NativeEvent&lt; NwModule, OnPlayerDying &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerequipitem_20_3e_496',['NativeEvent&lt; NwModule, OnPlayerEquipItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerlevelup_20_3e_497',['NativeEvent&lt; NwModule, OnPlayerLevelUp &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerrespawn_20_3e_498',['NativeEvent&lt; NwModule, OnPlayerRespawn &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerrest_20_3e_499',['NativeEvent&lt; NwModule, OnPlayerRest &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayertarget_20_3e_500',['NativeEvent&lt; NwModule, OnPlayerTarget &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onplayerunequipitem_20_3e_501',['NativeEvent&lt; NwModule, OnPlayerUnequipItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onunacquireitem_20_3e_502',['NativeEvent&lt; NwModule, OnUnacquireItem &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwmodule_2c_20onuserdefined_20_3e_503',['NativeEvent&lt; NwModule, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onclose_20_3e_504',['NativeEvent&lt; NwPlaceable, OnClose &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondamaged_20_3e_505',['NativeEvent&lt; NwPlaceable, OnDamaged &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondeath_20_3e_506',['NativeEvent&lt; NwPlaceable, OnDeath &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondialogue_20_3e_507',['NativeEvent&lt; NwPlaceable, OnDialogue &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondisarm_20_3e_508',['NativeEvent&lt; NwPlaceable, OnDisarm &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ondisturbed_20_3e_509',['NativeEvent&lt; NwPlaceable, OnDisturbed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onheartbeat_20_3e_510',['NativeEvent&lt; NwPlaceable, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onleftclick_20_3e_511',['NativeEvent&lt; NwPlaceable, OnLeftClick &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onlock_20_3e_512',['NativeEvent&lt; NwPlaceable, OnLock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onopen_20_3e_513',['NativeEvent&lt; NwPlaceable, OnOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onphysicalattacked_20_3e_514',['NativeEvent&lt; NwPlaceable, OnPhysicalAttacked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onspellcastat_20_3e_515',['NativeEvent&lt; NwPlaceable, OnSpellCastAt &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20ontraptriggered_20_3e_516',['NativeEvent&lt; NwPlaceable, OnTrapTriggered &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onunlock_20_3e_517',['NativeEvent&lt; NwPlaceable, OnUnlock &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onused_20_3e_518',['NativeEvent&lt; NwPlaceable, OnUsed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwplaceable_2c_20onuserdefined_20_3e_519',['NativeEvent&lt; NwPlaceable, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwstore_2c_20onclose_20_3e_520',['NativeEvent&lt; NwStore, OnClose &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwstore_2c_20onopen_20_3e_521',['NativeEvent&lt; NwStore, OnOpen &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onclicked_20_3e_522',['NativeEvent&lt; NwTrigger, OnClicked &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20ondisarmed_20_3e_523',['NativeEvent&lt; NwTrigger, OnDisarmed &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onenter_20_3e_524',['NativeEvent&lt; NwTrigger, OnEnter &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onexit_20_3e_525',['NativeEvent&lt; NwTrigger, OnExit &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onheartbeat_20_3e_526',['NativeEvent&lt; NwTrigger, OnHeartbeat &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20ontraptriggered_20_3e_527',['NativeEvent&lt; NwTrigger, OnTrapTriggered &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeevent_3c_20nwtrigger_2c_20onuserdefined_20_3e_528',['NativeEvent&lt; NwTrigger, OnUserDefined &gt;',['../classNWN_1_1API_1_1Events_1_1NativeEvent.html',1,'NWN::API::Events']]],
  ['nativeeventattribute_529',['NativeEventAttribute',['../classNWN_1_1API_1_1Events_1_1NativeEventAttribute.html',1,'NWN::API::Events']]],
  ['nativeeventservice_530',['NativeEventService',['../classNWN_1_1Services_1_1NativeEventService.html',1,'NWN::Services']]],
  ['nativescript_531',['NativeScript',['../classNWN_1_1API_1_1NativeScript.html',1,'NWN::API']]],
  ['newleader_532',['NewLeader',['../classNWNX_1_1API_1_1Events_1_1PartyEvents_1_1OnTransferLeadershipBefore.html#a6578f2be0fea5218636735fe87a43473',1,'NWNX.API.Events.PartyEvents.OnTransferLeadershipBefore.NewLeader()'],['../classNWNX_1_1API_1_1Events_1_1PartyEvents_1_1OnTransferLeadershipAfter.html#a0b8d7f113ccbc3c6ba71dfd2193885ce',1,'NWNX.API.Events.PartyEvents.OnTransferLeadershipAfter.NewLeader()']]],
  ['newtomodule_533',['NewToModule',['../classNWNX_1_1API_1_1Events_1_1ServerSendAreaEvents_1_1OnServerSendAreaBefore.html#a978dd1d8faff96683afcdbf268e4a8a8',1,'NWNX.API.Events.ServerSendAreaEvents.OnServerSendAreaBefore.NewToModule()'],['../classNWNX_1_1API_1_1Events_1_1ServerSendAreaEvents_1_1OnServerSendAreaAfter.html#ac51fbd07b5a364197643d4f81123ae35',1,'NWNX.API.Events.ServerSendAreaEvents.OnServerSendAreaAfter.NewToModule()']]],
  ['nextdouble_534',['NextDouble',['../classNWN_1_1API_1_1RandomExtensions.html#ad8dd4f09c4629e8a34ab4111052c2307',1,'NWN::API::RandomExtensions']]],
  ['nextfloat_535',['NextFloat',['../classNWN_1_1API_1_1RandomExtensions.html#ae56c7315f39fb225ab4c402c991a4c68',1,'NWN.API.RandomExtensions.NextFloat(this Random random)'],['../classNWN_1_1API_1_1RandomExtensions.html#a30a99195dac7180c94ae1edacdc36f4a',1,'NWN.API.RandomExtensions.NextFloat(this Random random, float minValue, float maxValue)']]],
  ['nextframe_536',['NextFrame',['../classNWN_1_1API_1_1NwTask.html#a9f4e6db66a44b051a6f98b76dbd88fb4',1,'NWN::API::NwTask']]],
  ['nighttoday_537',['NightToDay',['../classNWN_1_1API_1_1NwPlayer.html#a21fefcbd1d72624b17bb6ff526eb49f5',1,'NWN::API::NwPlayer']]],
  ['nmanager_538',['NManager',['../classNWN_1_1NManager.html',1,'NWN']]],
  ['now_539',['Now',['../structNWN_1_1Services_1_1NwDateTime.html#a3dc311a7f156ddbb90f9a916dc38915a',1,'NWN::Services::NwDateTime']]],
  ['nwarea_540',['NwArea',['../classNWN_1_1API_1_1NwArea.html',1,'NWN::API']]],
  ['nwareaofeffect_541',['NwAreaOfEffect',['../classNWN_1_1API_1_1NwAreaOfEffect.html',1,'NWN::API']]],
  ['nwcreature_542',['NwCreature',['../classNWN_1_1API_1_1NwCreature.html',1,'NWN::API']]],
  ['nwdatetime_543',['NwDateTime',['../structNWN_1_1Services_1_1NwDateTime.html',1,'NWN::Services']]],
  ['nwdoor_544',['NwDoor',['../classNWN_1_1API_1_1NwDoor.html',1,'NWN::API']]],
  ['nwencounter_545',['NwEncounter',['../classNWN_1_1API_1_1NwEncounter.html',1,'NWN::API']]],
  ['nwfaction_546',['NwFaction',['../classNWN_1_1API_1_1NwFaction.html',1,'NWN::API']]],
  ['nwgameobject_547',['NwGameObject',['../classNWN_1_1API_1_1NwGameObject.html',1,'NWN::API']]],
  ['nwitem_548',['NwItem',['../classNWN_1_1API_1_1NwItem.html',1,'NWN::API']]],
  ['nwmath_549',['NwMath',['../classNWN_1_1API_1_1NwMath.html',1,'NWN::API']]],
  ['nwmodule_550',['NwModule',['../classNWN_1_1API_1_1NwModule.html',1,'NWN::API']]],
  ['nwn_551',['NWN',['../namespaceNWN.html',1,'']]],
  ['nwnx_552',['NWNX',['../namespaceNWNX.html',1,'']]],
  ['nwnxattackeventattribute_553',['NWNXAttackEventAttribute',['../classNWNX_1_1API_1_1Events_1_1NWNXAttackEventAttribute.html',1,'NWNX::API::Events']]],
  ['nwnxdamageeventattribute_554',['NWNXDamageEventAttribute',['../classNWNX_1_1API_1_1Events_1_1NWNXDamageEventAttribute.html',1,'NWNX::API::Events']]],
  ['nwnxevent_555',['NWNXEvent',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX.API.Events.NWNXEvent'],['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX.API.Events.NWNXEvent&lt; T &gt;']]],
  ['nwnxevent_3c_20attackevent_20_3e_556',['NWNXEvent&lt; AttackEvent &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20damageevent_20_3e_557',['NWNXEvent&lt; DamageEvent &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onaddassociateafter_20_3e_558',['NWNXEvent&lt; OnAddAssociateAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onaddassociatebefore_20_3e_559',['NWNXEvent&lt; OnAddAssociateBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendardawn_20_3e_560',['NWNXEvent&lt; OnCalendarDawn &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendarday_20_3e_561',['NWNXEvent&lt; OnCalendarDay &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendardusk_20_3e_562',['NWNXEvent&lt; OnCalendarDusk &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendarhour_20_3e_563',['NWNXEvent&lt; OnCalendarHour &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendarmonth_20_3e_564',['NWNXEvent&lt; OnCalendarMonth &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20oncalendaryear_20_3e_565',['NWNXEvent&lt; OnCalendarYear &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onenterstealthafter_20_3e_566',['NWNXEvent&lt; OnEnterStealthAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onenterstealthbefore_20_3e_567',['NWNXEvent&lt; OnEnterStealthBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexamineobjectafter_20_3e_568',['NWNXEvent&lt; OnExamineObjectAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexamineobjectbefore_20_3e_569',['NWNXEvent&lt; OnExamineObjectBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexitstealthafter_20_3e_570',['NWNXEvent&lt; OnExitStealthAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onexitstealthbefore_20_3e_571',['NWNXEvent&lt; OnExitStealthBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onremoveassociateafter_20_3e_572',['NWNXEvent&lt; OnRemoveAssociateAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onremoveassociatebefore_20_3e_573',['NWNXEvent&lt; OnRemoveAssociateBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onservercharactersaveafter_20_3e_574',['NWNXEvent&lt; OnServerCharacterSaveAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onserversendareaafter_20_3e_575',['NWNXEvent&lt; OnServerSendAreaAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onserversendareabefore_20_3e_576',['NWNXEvent&lt; OnServerSendAreaBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestbuyafter_20_3e_577',['NWNXEvent&lt; OnStoreRequestBuyAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestbuybefore_20_3e_578',['NWNXEvent&lt; OnStoreRequestBuyBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestsellafter_20_3e_579',['NWNXEvent&lt; OnStoreRequestSellAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onstorerequestsellbefore_20_3e_580',['NWNXEvent&lt; OnStoreRequestSellBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onvalidateequipitemafter_20_3e_581',['NWNXEvent&lt; OnValidateEquipItemAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20onvalidateuseitemafter_20_3e_582',['NWNXEvent&lt; OnValidateUseItemAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxevent_3c_20t_20_3e_583',['NWNXEvent&lt; T &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEvent.html',1,'NWNX::API::Events']]],
  ['nwnxeventattribute_584',['NWNXEventAttribute',['../classNWNX_1_1API_1_1Events_1_1NWNXEventAttribute.html',1,'NWNX::API::Events']]],
  ['nwnxeventservice_585',['NWNXEventService',['../classNWNX_1_1Services_1_1NWNXEventService.html',1,'NWNX::Services']]],
  ['nwnxeventskippable_586',['NWNXEventSkippable',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onacceptinvitationafter_20_3e_587',['NWNXEventSkippable&lt; OnAcceptInvitationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onacceptinvitationbefore_20_3e_588',['NWNXEventSkippable&lt; OnAcceptInvitationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onbarterstartafter_20_3e_589',['NWNXEventSkippable&lt; OnBarterStartAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onbarterstartbefore_20_3e_590',['NWNXEventSkippable&lt; OnBarterStartBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientconnectafter_20_3e_591',['NWNXEventSkippable&lt; OnClientConnectAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientconnectbefore_20_3e_592',['NWNXEventSkippable&lt; OnClientConnectBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientdisconnectafter_20_3e_593',['NWNXEventSkippable&lt; OnClientDisconnectAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onclientdisconnectbefore_20_3e_594',['NWNXEventSkippable&lt; OnClientDisconnectBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onhealafter_20_3e_595',['NWNXEventSkippable&lt; OnHealAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onhealbefore_20_3e_596',['NWNXEventSkippable&lt; OnHealBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onignoreinvitationafter_20_3e_597',['NWNXEventSkippable&lt; OnIgnoreInvitationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onignoreinvitationbefore_20_3e_598',['NWNXEventSkippable&lt; OnIgnoreInvitationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryaddgoldafter_20_3e_599',['NWNXEventSkippable&lt; OnInventoryAddGoldAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryaddgoldbefore_20_3e_600',['NWNXEventSkippable&lt; OnInventoryAddGoldBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventorycloseafter_20_3e_601',['NWNXEventSkippable&lt; OnInventoryCloseAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryclosebefore_20_3e_602',['NWNXEventSkippable&lt; OnInventoryCloseBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryopenafter_20_3e_603',['NWNXEventSkippable&lt; OnInventoryOpenAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryopenbefore_20_3e_604',['NWNXEventSkippable&lt; OnInventoryOpenBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryremovegoldafter_20_3e_605',['NWNXEventSkippable&lt; OnInventoryRemoveGoldAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninventoryremovegoldbefore_20_3e_606',['NWNXEventSkippable&lt; OnInventoryRemoveGoldBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninviteafter_20_3e_607',['NWNXEventSkippable&lt; OnInviteAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20oninvitebefore_20_3e_608',['NWNXEventSkippable&lt; OnInviteBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitemequipbefore_20_3e_609',['NWNXEventSkippable&lt; OnItemEquipBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitempaytoidentifyafter_20_3e_610',['NWNXEventSkippable&lt; OnItemPayToIdentifyAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitempaytoidentifybefore_20_3e_611',['NWNXEventSkippable&lt; OnItemPayToIdentifyBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onitemusebefore_20_3e_612',['NWNXEventSkippable&lt; OnItemUseBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickafter_20_3e_613',['NWNXEventSkippable&lt; OnKickAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickbefore_20_3e_614',['NWNXEventSkippable&lt; OnKickBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickhenchmanafter_20_3e_615',['NWNXEventSkippable&lt; OnKickHenchmanAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onkickhenchmanbefore_20_3e_616',['NWNXEventSkippable&lt; OnKickHenchmanBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleaveafter_20_3e_617',['NWNXEventSkippable&lt; OnLeaveAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleavebefore_20_3e_618',['NWNXEventSkippable&lt; OnLeaveBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleveldownafter_20_3e_619',['NWNXEventSkippable&lt; OnLevelDownAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onleveldownbefore_20_3e_620',['NWNXEventSkippable&lt; OnLevelDownBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupafter_20_3e_621',['NWNXEventSkippable&lt; OnLevelUpAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupautomaticafter_20_3e_622',['NWNXEventSkippable&lt; OnLevelUpAutomaticAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupautomaticbefore_20_3e_623',['NWNXEventSkippable&lt; OnLevelUpAutomaticBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onlevelupbefore_20_3e_624',['NWNXEventSkippable&lt; OnLevelUpBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onrejectinvitationafter_20_3e_625',['NWNXEventSkippable&lt; OnRejectInvitationAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onrejectinvitationbefore_20_3e_626',['NWNXEventSkippable&lt; OnRejectInvitationBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onresourceadded_20_3e_627',['NWNXEventSkippable&lt; OnResourceAdded &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onresourcemodified_20_3e_628',['NWNXEventSkippable&lt; OnResourceModified &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onresourceremoved_20_3e_629',['NWNXEventSkippable&lt; OnResourceRemoved &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onservercharactersavebefore_20_3e_630',['NWNXEventSkippable&lt; OnServerCharacterSaveBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onsetmemorizedspellslotbefore_20_3e_631',['NWNXEventSkippable&lt; OnSetMemorizedSpellSlotBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20ontransferleadershipafter_20_3e_632',['NWNXEventSkippable&lt; OnTransferLeadershipAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20ontransferleadershipbefore_20_3e_633',['NWNXEventSkippable&lt; OnTransferLeadershipBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onusefeatbefore_20_3e_634',['NWNXEventSkippable&lt; OnUseFeatBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onvalidateafter_20_3e_635',['NWNXEventSkippable&lt; OnValidateAfter &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwnxeventskippable_3c_20onvalidatebefore_20_3e_636',['NWNXEventSkippable&lt; OnValidateBefore &gt;',['../classNWNX_1_1API_1_1Events_1_1NWNXEventSkippable.html',1,'NWNX::API::Events']]],
  ['nwobject_637',['NwObject',['../classNWN_1_1API_1_1NwObject.html',1,'NWN::API']]],
  ['nwplaceable_638',['NwPlaceable',['../classNWN_1_1API_1_1NwPlaceable.html',1,'NWN::API']]],
  ['nwplayer_639',['NwPlayer',['../classNWN_1_1API_1_1NwPlayer.html',1,'NWN::API']]],
  ['nwrandom_640',['NwRandom',['../classNWN_1_1API_1_1NwRandom.html',1,'NWN::API']]],
  ['nwsound_641',['NwSound',['../classNWN_1_1API_1_1NwSound.html',1,'NWN::API']]],
  ['nwstationary_642',['NwStationary',['../classNWN_1_1API_1_1NwStationary.html',1,'NWN::API']]],
  ['nwstore_643',['NwStore',['../classNWN_1_1API_1_1NwStore.html',1,'NWN::API']]],
  ['nwtask_644',['NwTask',['../classNWN_1_1API_1_1NwTask.html',1,'NWN::API']]],
  ['nwtimespan_645',['NwTimeSpan',['../classNWN_1_1API_1_1NwTimeSpan.html',1,'NWN::API']]],
  ['nwtrappable_646',['NwTrappable',['../classNWN_1_1API_1_1NwTrappable.html',1,'NWN::API']]],
  ['nwtrigger_647',['NwTrigger',['../classNWN_1_1API_1_1NwTrigger.html',1,'NWN::API']]],
  ['nwwaypoint_648',['NwWaypoint',['../classNWN_1_1API_1_1NwWaypoint.html',1,'NWN::API']]],
  ['plugins_649',['Plugins',['../namespaceNWN_1_1Plugins.html',1,'NWN']]],
  ['services_650',['Services',['../namespaceNWN_1_1Services.html',1,'NWN.Services'],['../namespaceNWNX_1_1Services.html',1,'NWNX.Services']]]
];
