using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPDamageReduction
  {
    DR1 = NWScript.IP_CONST_DAMAGEREDUCTION_1,
    DR2 = NWScript.IP_CONST_DAMAGEREDUCTION_2,
    DR3 = NWScript.IP_CONST_DAMAGEREDUCTION_3,
    DR4 = NWScript.IP_CONST_DAMAGEREDUCTION_4,
    DR5 = NWScript.IP_CONST_DAMAGEREDUCTION_5,
    DR6 = NWScript.IP_CONST_DAMAGEREDUCTION_6,
    DR7 = NWScript.IP_CONST_DAMAGEREDUCTION_7,
    DR8 = NWScript.IP_CONST_DAMAGEREDUCTION_8,
    DR9 = NWScript.IP_CONST_DAMAGEREDUCTION_9,
    DR10 = NWScript.IP_CONST_DAMAGEREDUCTION_10,
    DR11 = NWScript.IP_CONST_DAMAGEREDUCTION_11,
    DR12 = NWScript.IP_CONST_DAMAGEREDUCTION_12,
    DR13 = NWScript.IP_CONST_DAMAGEREDUCTION_13,
    DR14 = NWScript.IP_CONST_DAMAGEREDUCTION_14,
    DR15 = NWScript.IP_CONST_DAMAGEREDUCTION_15,
    DR16 = NWScript.IP_CONST_DAMAGEREDUCTION_16,
    DR17 = NWScript.IP_CONST_DAMAGEREDUCTION_17,
    DR18 = NWScript.IP_CONST_DAMAGEREDUCTION_18,
    DR19 = NWScript.IP_CONST_DAMAGEREDUCTION_19,
    DR20 = NWScript.IP_CONST_DAMAGEREDUCTION_20,
  }
}
