using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPDamageImmunityType
  {
    Immunity5Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_5_PERCENT,
    Immunity10Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_10_PERCENT,
    Immunity25Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_25_PERCENT,
    Immunity50Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_50_PERCENT,
    Immunity75Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_75_PERCENT,
    Immunity90Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_90_PERCENT,
    Immunity100Pct = NWScript.IP_CONST_DAMAGEIMMUNITY_100_PERCENT
  }
}