using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPFeat
  {
    Alertness = NWScript.IP_CONST_FEAT_ALERTNESS,
    Ambidextrous = NWScript.IP_CONST_FEAT_AMBIDEXTROUS,
    Cleave = NWScript.IP_CONST_FEAT_CLEAVE,
    CombatCasting = NWScript.IP_CONST_FEAT_COMBAT_CASTING,
    Dodge = NWScript.IP_CONST_FEAT_DODGE,
    ExtraTurning = NWScript.IP_CONST_FEAT_EXTRA_TURNING,
    Knockdown = NWScript.IP_CONST_FEAT_KNOCKDOWN,
    PointBlank = NWScript.IP_CONST_FEAT_POINTBLANK,
    SpellFocusAbjuration = NWScript.IP_CONST_FEAT_SPELLFOCUSABJ,
    SpellFocusConstitution = NWScript.IP_CONST_FEAT_SPELLFOCUSCON,
    SpellFocusDivination = NWScript.IP_CONST_FEAT_SPELLFOCUSDIV,
    SpellFocusEnchantment = NWScript.IP_CONST_FEAT_SPELLFOCUSENC,
    SpellFocusEvocation = NWScript.IP_CONST_FEAT_SPELLFOCUSEVO,
    SpellFocusIllusion = NWScript.IP_CONST_FEAT_SPELLFOCUSILL,
    SpellFocusNecromancy = NWScript.IP_CONST_FEAT_SPELLFOCUSNEC,
    SpellPenetration = NWScript.IP_CONST_FEAT_SPELLPENETRATION,
    PowerAttack = NWScript.IP_CONST_FEAT_POWERATTACK,
    TwoWeaponFighting = NWScript.IP_CONST_FEAT_TWO_WEAPON_FIGHTING,
    WeaponSpecializationUnarmed = NWScript.IP_CONST_FEAT_WEAPSPEUNARM,
    WeaponFinesse = NWScript.IP_CONST_FEAT_WEAPFINESSE,
    ImprovedCriticalUnarmed = NWScript.IP_CONST_FEAT_IMPCRITUNARM,
    WeaponProfExotic = NWScript.IP_CONST_FEAT_WEAPON_PROF_EXOTIC,
    WeaponProfMartial = NWScript.IP_CONST_FEAT_WEAPON_PROF_MARTIAL,
    WeaponProfSimple = NWScript.IP_CONST_FEAT_WEAPON_PROF_SIMPLE,
    ArmorProfHeavy = NWScript.IP_CONST_FEAT_ARMOR_PROF_HEAVY,
    ArmorProfLight = NWScript.IP_CONST_FEAT_ARMOR_PROF_LIGHT,
    ArmorProfMedium = NWScript.IP_CONST_FEAT_ARMOR_PROF_MEDIUM,
    Mobility = NWScript.IP_CONST_FEAT_MOBILITY,
    Disarm = NWScript.IP_CONST_FEAT_DISARM,
    Whirlwind = NWScript.IP_CONST_FEAT_WHIRLWIND,
    RapidShot = NWScript.IP_CONST_FEAT_RAPID_SHOT,
    HideInPlainSight = NWScript.IP_CONST_FEAT_HIDE_IN_PLAIN_SIGHT,
    SneakAttack1D6 = NWScript.IP_CONST_FEAT_SNEAK_ATTACK_1D6,
    SneakAttack2D6 = NWScript.IP_CONST_FEAT_SNEAK_ATTACK_2D6,
    SneakAttack3D6 = NWScript.IP_CONST_FEAT_SNEAK_ATTACK_3D6,
    ShieldProficiency = NWScript.IP_CONST_FEAT_SHIELD_PROFICIENCY,
    UsePoison = NWScript.IP_CONST_FEAT_USE_POISON,
    DisarmWhip = NWScript.IP_CONST_FEAT_DISARM_WHIP,
    WeaponProfCreature = NWScript.IP_CONST_FEAT_WEAPON_PROF_CREATURE,
    SneakAttack5D6 = NWScript.IP_CONST_FEAT_SNEAK_ATTACK_5D6,
    PlayerTool01 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_01,
    PlayerTool02 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_02,
    PlayerTool03 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_03,
    PlayerTool04 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_04,
    PlayerTool05 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_05,
    PlayerTool06 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_06,
    PlayerTool07 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_07,
    PlayerTool08 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_08,
    PlayerTool09 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_09,
    PlayerTool10 = NWScript.IP_CONST_FEAT_PLAYER_TOOL_10
  }
}