using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPMiscImmunity
  {
    BackStab = NWScript.IP_CONST_IMMUNITYMISC_BACKSTAB,
    LevelAbilityDrain = NWScript.IP_CONST_IMMUNITYMISC_LEVEL_ABIL_DRAIN,
    MindSpells = NWScript.IP_CONST_IMMUNITYMISC_MINDSPELLS,
    Poison = NWScript.IP_CONST_IMMUNITYMISC_POISON,
    Disease = NWScript.IP_CONST_IMMUNITYMISC_DISEASE,
    Fear = NWScript.IP_CONST_IMMUNITYMISC_FEAR,
    Knockdown = NWScript.IP_CONST_IMMUNITYMISC_KNOCKDOWN,
    Paralysis = NWScript.IP_CONST_IMMUNITYMISC_PARALYSIS,
    CriticalHits = NWScript.IP_CONST_IMMUNITYMISC_CRITICAL_HITS,
    DeathMagic = NWScript.IP_CONST_IMMUNITYMISC_DEATH_MAGIC
  }
}