using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPSpellResistanceBonus
  {
    Plus10 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_10,
    Plus12 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_12,
    Plus14 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_14,
    Plus16 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_16,
    Plus18 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_18,
    Plus20 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_20,
    Plus22 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_22,
    Plus24 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_24,
    Plus26 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_26,
    Plus28 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_28,
    Plus30 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_30,
    Plus32 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_32
  }
}
