using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPSpellLevel
  {
    SL0 = NWScript.IP_CONST_SPELLLEVEL_0,
    SL1 = NWScript.IP_CONST_SPELLLEVEL_1,
    SL2 = NWScript.IP_CONST_SPELLLEVEL_2,
    SL3 = NWScript.IP_CONST_SPELLLEVEL_3,
    SL4 = NWScript.IP_CONST_SPELLLEVEL_4,
    SL5 = NWScript.IP_CONST_SPELLLEVEL_5,
    SL6 = NWScript.IP_CONST_SPELLLEVEL_6,
    SL7 = NWScript.IP_CONST_SPELLLEVEL_7,
    SL8 = NWScript.IP_CONST_SPELLLEVEL_8,
    SL9 = NWScript.IP_CONST_SPELLLEVEL_9,
  }
}
