using NWN.Core;

namespace NWN.API.Constants
{
  public enum IPUnlimitedAmmoType
  {
    Basic = NWScript.IP_CONST_UNLIMITEDAMMO_BASIC,
    Fire1d6 = NWScript.IP_CONST_UNLIMITEDAMMO_1D6FIRE,
    Cold1d6 = NWScript.IP_CONST_UNLIMITEDAMMO_1D6COLD,
    Light1d6 = NWScript.IP_CONST_UNLIMITEDAMMO_1D6LIGHT,
    Plus1 = NWScript.IP_CONST_UNLIMITEDAMMO_PLUS1,
    Plus2 = NWScript.IP_CONST_UNLIMITEDAMMO_PLUS2,
    Plus3 = NWScript.IP_CONST_UNLIMITEDAMMO_PLUS3,
    Plus4 = NWScript.IP_CONST_UNLIMITEDAMMO_PLUS4,
    Plus5 = NWScript.IP_CONST_UNLIMITEDAMMO_PLUS5
  }
}
