using NWN.Core;

namespace Anvil.API
{
  public enum IPOnMonsterHit
  {
    AbilityDrain = NWScript.IP_CONST_ONMONSTERHIT_ABILITYDRAIN,
    Confusion = NWScript.IP_CONST_ONMONSTERHIT_CONFUSION,
    Disease = NWScript.IP_CONST_ONMONSTERHIT_DISEASE,
    Doom = NWScript.IP_CONST_ONMONSTERHIT_DOOM,
    Fear = NWScript.IP_CONST_ONMONSTERHIT_FEAR,
    LevelDrain = NWScript.IP_CONST_ONMONSTERHIT_LEVELDRAIN,
    Poison = NWScript.IP_CONST_ONMONSTERHIT_POISON,
    Slow = NWScript.IP_CONST_ONMONSTERHIT_SLOW,
    Stun = NWScript.IP_CONST_ONMONSTERHIT_STUN,
    Wounding = NWScript.IP_CONST_ONMONSTERHIT_WOUNDING,
  }
}
