using System;
using NWN.Core;

namespace Anvil.API
{
  [Obsolete("Use RacialType instead.")]
  public enum IPRacialType
  {
    Dwarf = NWScript.IP_CONST_RACIALTYPE_DWARF,
    Elf = NWScript.IP_CONST_RACIALTYPE_ELF,
    Gnome = NWScript.IP_CONST_RACIALTYPE_GNOME,
    Halfling = NWScript.IP_CONST_RACIALTYPE_HALFLING,
    HalfElf = NWScript.IP_CONST_RACIALTYPE_HALFELF,
    HalfOrc = NWScript.IP_CONST_RACIALTYPE_HALFORC,
    Human = NWScript.IP_CONST_RACIALTYPE_HUMAN,
    Aberration = NWScript.IP_CONST_RACIALTYPE_ABERRATION,
    Animal = NWScript.IP_CONST_RACIALTYPE_ANIMAL,
    Beast = NWScript.IP_CONST_RACIALTYPE_BEAST,
    Construct = NWScript.IP_CONST_RACIALTYPE_CONSTRUCT,
    Dragon = NWScript.IP_CONST_RACIALTYPE_DRAGON,
    HumanoidGoblinoid = NWScript.IP_CONST_RACIALTYPE_HUMANOID_GOBLINOID,
    HumanoidMonstrous = NWScript.IP_CONST_RACIALTYPE_HUMANOID_MONSTROUS,
    HumanoidOrc = NWScript.IP_CONST_RACIALTYPE_HUMANOID_ORC,
    HumanoidReptilian = NWScript.IP_CONST_RACIALTYPE_HUMANOID_REPTILIAN,
    Elemental = NWScript.IP_CONST_RACIALTYPE_ELEMENTAL,
    Fey = NWScript.IP_CONST_RACIALTYPE_FEY,
    Giant = NWScript.IP_CONST_RACIALTYPE_GIANT,
    MagicalBeast = NWScript.IP_CONST_RACIALTYPE_MAGICAL_BEAST,
    Outsider = NWScript.IP_CONST_RACIALTYPE_OUTSIDER,
    ShapeChanger = NWScript.IP_CONST_RACIALTYPE_SHAPECHANGER,
    Undead = NWScript.IP_CONST_RACIALTYPE_UNDEAD,
    Vermin = NWScript.IP_CONST_RACIALTYPE_VERMIN,
  }
}
