using NWN.Core;

namespace Anvil.API
{
  public enum VisualTransformLerpType
  {
    None = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_NONE,
    Linear = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_LINEAR,
    SmoothStep = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_SMOOTHSTEP,
    InverseSmoothStep = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_INVERSE_SMOOTHSTEP,
    EaseIn = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_EASE_IN,
    EaseOut = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_EASE_OUT,
    Quadratic = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_QUADRATIC,
    SmootherStep = NWScript.OBJECT_VISUAL_TRANSFORM_LERP_SMOOTHERSTEP,
  }
}
