using NWN.Core;

namespace NWN.API.Constants
{
  public enum TalentCategory
  {
    HarmfulAreaEffectDiscriminant = NWScript.TALENT_CATEGORY_HARMFUL_AREAEFFECT_DISCRIMINANT,
    HarmfulRanged = NWScript.TALENT_CATEGORY_HARMFUL_RANGED,
    HarmfulTouch = NWScript.TALENT_CATEGORY_HARMFUL_TOUCH,
    BeneficialHealingAreaEffect = NWScript.TALENT_CATEGORY_BENEFICIAL_HEALING_AREAEFFECT,
    BeneficialHealingTouch = NWScript.TALENT_CATEGORY_BENEFICIAL_HEALING_TOUCH,
    BeneficialConditionalAreaEffect = NWScript.TALENT_CATEGORY_BENEFICIAL_CONDITIONAL_AREAEFFECT,
    BeneficialConditionalSingle = NWScript.TALENT_CATEGORY_BENEFICIAL_CONDITIONAL_SINGLE,
    BeneficialEnhancementAreaEffect = NWScript.TALENT_CATEGORY_BENEFICIAL_ENHANCEMENT_AREAEFFECT,
    BeneficialEnhancementSingle = NWScript.TALENT_CATEGORY_BENEFICIAL_ENHANCEMENT_SINGLE,
    BeneficialEnhancementSelf = NWScript.TALENT_CATEGORY_BENEFICIAL_ENHANCEMENT_SELF,
    HarmfulAreaEffectIndiscriminant = NWScript.TALENT_CATEGORY_HARMFUL_AREAEFFECT_INDISCRIMINANT,
    BeneficialProtectionSelf = NWScript.TALENT_CATEGORY_BENEFICIAL_PROTECTION_SELF,
    BeneficialProtectionSingle = NWScript.TALENT_CATEGORY_BENEFICIAL_PROTECTION_SINGLE,
    BeneficialProtectionAreaEffect = NWScript.TALENT_CATEGORY_BENEFICIAL_PROTECTION_AREAEFFECT,
    BeneficialObtainAllies = NWScript.TALENT_CATEGORY_BENEFICIAL_OBTAIN_ALLIES,
    PersistentAreaOfEffect = NWScript.TALENT_CATEGORY_PERSISTENT_AREA_OF_EFFECT,
    BeneficialHealingPotion = NWScript.TALENT_CATEGORY_BENEFICIAL_HEALING_POTION,
    BeneficialConditionalPotion = NWScript.TALENT_CATEGORY_BENEFICIAL_CONDITIONAL_POTION,
    DragonsBreath = NWScript.TALENT_CATEGORY_DRAGONS_BREATH,
    BeneficialProtectionPotion = NWScript.TALENT_CATEGORY_BENEFICIAL_PROTECTION_POTION,
    BeneficialEnhancementPotion = NWScript.TALENT_CATEGORY_BENEFICIAL_ENHANCEMENT_POTION,
    HarmfulMelee = NWScript.TALENT_CATEGORY_HARMFUL_MELEE,
  }
}
