using NWN.Core;

namespace NWM.API.Constants
{
  public enum AnimalCompanionCreatureType
  {
    Badger = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_BADGER,
    Wolf = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_WOLF,
    Bear = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_BEAR,
    Boar = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_BOAR,
    Hawk = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_HAWK,
    Panther = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_PANTHER,
    Spider = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_SPIDER,
    DireWolf = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_DIREWOLF,
    DireRat = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_DIRERAT,
    None = NWScript.ANIMAL_COMPANION_CREATURE_TYPE_NONE
  }
}