using NWN;

namespace NWM.API.Constants
{
  public enum ClassType
  {
    Barbarian = NWScript.CLASS_TYPE_BARBARIAN,
    Bard = NWScript.CLASS_TYPE_BARD,
    Cleric = NWScript.CLASS_TYPE_CLERIC,
    Druid = NWScript.CLASS_TYPE_DRUID,
    Fighter = NWScript.CLASS_TYPE_FIGHTER,
    Monk = NWScript.CLASS_TYPE_MONK,
    Paladin = NWScript.CLASS_TYPE_PALADIN,
    Ranger = NWScript.CLASS_TYPE_RANGER,
    Rogue = NWScript.CLASS_TYPE_ROGUE,
    Sorcerer = NWScript.CLASS_TYPE_SORCERER,
    Wizard = NWScript.CLASS_TYPE_WIZARD,
    Aberration = NWScript.CLASS_TYPE_ABERRATION,
    Animal = NWScript.CLASS_TYPE_ANIMAL,
    Construct = NWScript.CLASS_TYPE_CONSTRUCT,
    Humanoid = NWScript.CLASS_TYPE_HUMANOID,
    Monstrous = NWScript.CLASS_TYPE_MONSTROUS,
    Elemental = NWScript.CLASS_TYPE_ELEMENTAL,
    Fey = NWScript.CLASS_TYPE_FEY,
    Dragon = NWScript.CLASS_TYPE_DRAGON,
    Undead = NWScript.CLASS_TYPE_UNDEAD,
    Commoner = NWScript.CLASS_TYPE_COMMONER,
    Beast = NWScript.CLASS_TYPE_BEAST,
    Giant = NWScript.CLASS_TYPE_GIANT,
    MagicalBeast = NWScript.CLASS_TYPE_MAGICAL_BEAST,
    Outsider = NWScript.CLASS_TYPE_OUTSIDER,
    Shapechanger = NWScript.CLASS_TYPE_SHAPECHANGER,
    Vermin = NWScript.CLASS_TYPE_VERMIN,
    Shadowdancer = NWScript.CLASS_TYPE_SHADOWDANCER,
    Harper = NWScript.CLASS_TYPE_HARPER,
    ArcaneArcher = NWScript.CLASS_TYPE_ARCANE_ARCHER,
    Assassin = NWScript.CLASS_TYPE_ASSASSIN,
    Blackguard = NWScript.CLASS_TYPE_BLACKGUARD,
    DivineChampion = NWScript.CLASS_TYPE_DIVINE_CHAMPION,
    WeaponMaster = NWScript.CLASS_TYPE_WEAPON_MASTER,
    PaleMaster = NWScript.CLASS_TYPE_PALE_MASTER,
    Shifter = NWScript.CLASS_TYPE_SHIFTER,
    DwarvenDefender = NWScript.CLASS_TYPE_DWARVEN_DEFENDER,
    DragonDisciple = NWScript.CLASS_TYPE_DRAGON_DISCIPLE,
    Ooze = NWScript.CLASS_TYPE_OOZE,
    EyeOfGruumsh = NWScript.CLASS_TYPE_EYE_OF_GRUUMSH,
    ShouDisciple = NWScript.CLASS_TYPE_SHOU_DISCIPLE,
    PurpleDragonKnight = NWScript.CLASS_TYPE_PURPLE_DRAGON_KNIGHT,
    Invalid = NWScript.CLASS_TYPE_INVALID
  }
}