using NWN.Core;

namespace NWM.API.Constants
{
  public enum FamiliarCreatureType
  {
    Bat = NWScript.FAMILIAR_CREATURE_TYPE_BAT,
    CragCat = NWScript.FAMILIAR_CREATURE_TYPE_CRAGCAT,
    HellHound = NWScript.FAMILIAR_CREATURE_TYPE_HELLHOUND,
    Imp = NWScript.FAMILIAR_CREATURE_TYPE_IMP,
    FireMephit = NWScript.FAMILIAR_CREATURE_TYPE_FIREMEPHIT,
    IceMephit = NWScript.FAMILIAR_CREATURE_TYPE_ICEMEPHIT,
    Pixie = NWScript.FAMILIAR_CREATURE_TYPE_PIXIE,
    Raven = NWScript.FAMILIAR_CREATURE_TYPE_RAVEN,
    FairyDragon = NWScript.FAMILIAR_CREATURE_TYPE_FAIRY_DRAGON,
    PseudoDragon = NWScript.FAMILIAR_CREATURE_TYPE_PSEUDO_DRAGON,
    Eyeball  = NWScript.FAMILIAR_CREATURE_TYPE_EYEBALL,
    None = NWScript.FAMILIAR_CREATURE_TYPE_NONE
  }
}