using NWN.Core;

namespace NWM.API.Constants
{
  public enum PersistentVfxType
  {
    PerFogacid = NWScript.AOE_PER_FOGACID,
    PerFogfire = NWScript.AOE_PER_FOGFIRE,
    PerFogstink = NWScript.AOE_PER_FOGSTINK,
    PerFogkill = NWScript.AOE_PER_FOGKILL,
    PerFogmind = NWScript.AOE_PER_FOGMIND,
    PerWallfire = NWScript.AOE_PER_WALLFIRE,
    PerWallwind = NWScript.AOE_PER_WALLWIND,
    PerWallblade = NWScript.AOE_PER_WALLBLADE,
    PerWeb = NWScript.AOE_PER_WEB,
    PerEntangle = NWScript.AOE_PER_ENTANGLE,
    PerDarkness = NWScript.AOE_PER_DARKNESS,
    MobCircevil = NWScript.AOE_MOB_CIRCEVIL,
    MobCircgood = NWScript.AOE_MOB_CIRCGOOD,
    MobCirclaw = NWScript.AOE_MOB_CIRCLAW,
    MobCircchaos = NWScript.AOE_MOB_CIRCCHAOS,
    MobFear = NWScript.AOE_MOB_FEAR,
    MobBlinding = NWScript.AOE_MOB_BLINDING,
    MobUnearthly = NWScript.AOE_MOB_UNEARTHLY,
    MobMenace = NWScript.AOE_MOB_MENACE,
    MobUnnatural = NWScript.AOE_MOB_UNNATURAL,
    MobStun = NWScript.AOE_MOB_STUN,
    MobProtection = NWScript.AOE_MOB_PROTECTION,
    MobFire = NWScript.AOE_MOB_FIRE,
    MobFrost = NWScript.AOE_MOB_FROST,
    MobElectrical = NWScript.AOE_MOB_ELECTRICAL,
    PerFogghoul = NWScript.AOE_PER_FOGGHOUL,
    MobTyrantFog = NWScript.AOE_MOB_TYRANT_FOG,
    PerStorm = NWScript.AOE_PER_STORM,
    PerInvisSphere = NWScript.AOE_PER_INVIS_SPHERE,
    MobSilence = NWScript.AOE_MOB_SILENCE,
    PerDelayBlastFireball = NWScript.AOE_PER_DELAY_BLAST_FIREBALL,
    PerGrease = NWScript.AOE_PER_GREASE,
    PerCreepingDoom = NWScript.AOE_PER_CREEPING_DOOM,
    PerEvardsBlackTentacles = NWScript.AOE_PER_EVARDS_BLACK_TENTACLES,
    MobInvisibilityPurge = NWScript.AOE_MOB_INVISIBILITY_PURGE,
    MobDragonFear = NWScript.AOE_MOB_DRAGON_FEAR,
    PerCustomAoe = NWScript.AOE_PER_CUSTOM_AOE,
    PerGlyphOfWarding = NWScript.AOE_PER_GLYPH_OF_WARDING,
    PerFogOfBewilderment = NWScript.AOE_PER_FOG_OF_BEWILDERMENT,
    PerVineMineCamouflage = NWScript.AOE_PER_VINE_MINE_CAMOUFLAGE,
    MobTideOfBattle = NWScript.AOE_MOB_TIDE_OF_BATTLE,
    PerStonehold = NWScript.AOE_PER_STONEHOLD,
    PerOvermind = NWScript.AOE_PER_OVERMIND,
    MobHorrificappearance = NWScript.AOE_MOB_HORRIFICAPPEARANCE,
    MobTroglodyteStench = NWScript.AOE_MOB_TROGLODYTE_STENCH
  }
}