using NWN.Core;

namespace NWM.API.Constants
{
  public enum PoisonType
  {
    Nightshade = NWScript.POISON_NIGHTSHADE,
    SmallCentipedePoison = NWScript.POISON_SMALL_CENTIPEDE_POISON,
    BladeBane = NWScript.POISON_BLADE_BANE,
    GreenbloodOil = NWScript.POISON_GREENBLOOD_OIL,
    Bloodroot = NWScript.POISON_BLOODROOT,
    PurpleWormPoison = NWScript.POISON_PURPLE_WORM_POISON,
    LargeScorpionVenom = NWScript.POISON_LARGE_SCORPION_VENOM,
    WyvernPoison = NWScript.POISON_WYVERN_POISON,
    BlueWhinnis = NWScript.POISON_BLUE_WHINNIS,
    GiantWaspPoison = NWScript.POISON_GIANT_WASP_POISON,
    ShadowEssence = NWScript.POISON_SHADOW_ESSENCE,
    BlackAdderVenom = NWScript.POISON_BLACK_ADDER_VENOM,
    Deathblade = NWScript.POISON_DEATHBLADE,
    MalyssRootPaste = NWScript.POISON_MALYSS_ROOT_PASTE,
    Nitharit = NWScript.POISON_NITHARIT,
    DragonBile = NWScript.POISON_DRAGON_BILE,
    SassoneLeafResidue = NWScript.POISON_SASSONE_LEAF_RESIDUE,
    TerinavRoot = NWScript.POISON_TERINAV_ROOT,
    CarrionCrawlerBrainJuice = NWScript.POISON_CARRION_CRAWLER_BRAIN_JUICE,
    BlackLotusExtract = NWScript.POISON_BLACK_LOTUS_EXTRACT,
    OilOfTaggit = NWScript.POISON_OIL_OF_TAGGIT,
    IdMoss = NWScript.POISON_ID_MOSS,
    StripedToadstool = NWScript.POISON_STRIPED_TOADSTOOL,
    Arsenic = NWScript.POISON_ARSENIC,
    LichDust = NWScript.POISON_LICH_DUST,
    DarkReaverPowder = NWScript.POISON_DARK_REAVER_POWDER,
    UngolDust = NWScript.POISON_UNGOL_DUST,
    BurntOthurFumes = NWScript.POISON_BURNT_OTHUR_FUMES,
    ChaosMist = NWScript.POISON_CHAOS_MIST,
    BebilithVenom = NWScript.POISON_BEBILITH_VENOM,
    QuasitVenom = NWScript.POISON_QUASIT_VENOM,
    PitFiendIchor = NWScript.POISON_PIT_FIEND_ICHOR,
    EttercapVenom = NWScript.POISON_ETTERCAP_VENOM,
    AraneaVenom = NWScript.POISON_ARANEA_VENOM,
    TinySpiderVenom = NWScript.POISON_TINY_SPIDER_VENOM,
    SmallSpiderVenom = NWScript.POISON_SMALL_SPIDER_VENOM,
    MediumSpiderVenom = NWScript.POISON_MEDIUM_SPIDER_VENOM,
    LargeSpiderVenom = NWScript.POISON_LARGE_SPIDER_VENOM,
    HugeSpiderVenom = NWScript.POISON_HUGE_SPIDER_VENOM,
    GargantuanSpiderVenom = NWScript.POISON_GARGANTUAN_SPIDER_VENOM,
    ColossalSpiderVenom = NWScript.POISON_COLOSSAL_SPIDER_VENOM,
    PhaseSpiderVenom = NWScript.POISON_PHASE_SPIDER_VENOM,
    WraithSpiderVenom = NWScript.POISON_WRAITH_SPIDER_VENOM,
    IronGolem = NWScript.POISON_IRON_GOLEM
  }
}