using NWN;

namespace NWM.API.Constants
{
  public enum TrapBaseType
  {
    MinorSpike = NWScript.TRAP_BASE_TYPE_MINOR_SPIKE,
    AverageSpike = NWScript.TRAP_BASE_TYPE_AVERAGE_SPIKE,
    StrongSpike = NWScript.TRAP_BASE_TYPE_STRONG_SPIKE,
    DeadlySpike = NWScript.TRAP_BASE_TYPE_DEADLY_SPIKE,
    MinorHoly = NWScript.TRAP_BASE_TYPE_MINOR_HOLY,
    AverageHoly = NWScript.TRAP_BASE_TYPE_AVERAGE_HOLY,
    StrongHoly = NWScript.TRAP_BASE_TYPE_STRONG_HOLY,
    DeadlyHoly = NWScript.TRAP_BASE_TYPE_DEADLY_HOLY,
    MinorTangle = NWScript.TRAP_BASE_TYPE_MINOR_TANGLE,
    AverageTangle = NWScript.TRAP_BASE_TYPE_AVERAGE_TANGLE,
    StrongTangle = NWScript.TRAP_BASE_TYPE_STRONG_TANGLE,
    DeadlyTangle = NWScript.TRAP_BASE_TYPE_DEADLY_TANGLE,
    MinorAcid = NWScript.TRAP_BASE_TYPE_MINOR_ACID,
    AverageAcid = NWScript.TRAP_BASE_TYPE_AVERAGE_ACID,
    StrongAcid = NWScript.TRAP_BASE_TYPE_STRONG_ACID,
    DeadlyAcid = NWScript.TRAP_BASE_TYPE_DEADLY_ACID,
    MinorFire = NWScript.TRAP_BASE_TYPE_MINOR_FIRE,
    AverageFire = NWScript.TRAP_BASE_TYPE_AVERAGE_FIRE,
    StrongFire = NWScript.TRAP_BASE_TYPE_STRONG_FIRE,
    DeadlyFire = NWScript.TRAP_BASE_TYPE_DEADLY_FIRE,
    MinorElectrical = NWScript.TRAP_BASE_TYPE_MINOR_ELECTRICAL,
    AverageElectrical = NWScript.TRAP_BASE_TYPE_AVERAGE_ELECTRICAL,
    StrongElectrical = NWScript.TRAP_BASE_TYPE_STRONG_ELECTRICAL,
    DeadlyElectrical = NWScript.TRAP_BASE_TYPE_DEADLY_ELECTRICAL,
    MinorGas = NWScript.TRAP_BASE_TYPE_MINOR_GAS,
    AverageGas = NWScript.TRAP_BASE_TYPE_AVERAGE_GAS,
    StrongGas = NWScript.TRAP_BASE_TYPE_STRONG_GAS,
    DeadlyGas = NWScript.TRAP_BASE_TYPE_DEADLY_GAS,
    MinorFrost = NWScript.TRAP_BASE_TYPE_MINOR_FROST,
    AverageFrost = NWScript.TRAP_BASE_TYPE_AVERAGE_FROST,
    StrongFrost = NWScript.TRAP_BASE_TYPE_STRONG_FROST,
    DeadlyFrost = NWScript.TRAP_BASE_TYPE_DEADLY_FROST,
    MinorNegative = NWScript.TRAP_BASE_TYPE_MINOR_NEGATIVE,
    AverageNegative = NWScript.TRAP_BASE_TYPE_AVERAGE_NEGATIVE,
    StrongNegative = NWScript.TRAP_BASE_TYPE_STRONG_NEGATIVE,
    DeadlyNegative = NWScript.TRAP_BASE_TYPE_DEADLY_NEGATIVE,
    MinorSonic = NWScript.TRAP_BASE_TYPE_MINOR_SONIC,
    AverageSonic = NWScript.TRAP_BASE_TYPE_AVERAGE_SONIC,
    StrongSonic = NWScript.TRAP_BASE_TYPE_STRONG_SONIC,
    DeadlySonic = NWScript.TRAP_BASE_TYPE_DEADLY_SONIC,
    MinorAcidSplash = NWScript.TRAP_BASE_TYPE_MINOR_ACID_SPLASH,
    AverageAcidSplash = NWScript.TRAP_BASE_TYPE_AVERAGE_ACID_SPLASH,
    StrongAcidSplash = NWScript.TRAP_BASE_TYPE_STRONG_ACID_SPLASH,
    DeadlyAcidSplash = NWScript.TRAP_BASE_TYPE_DEADLY_ACID_SPLASH,
    EpicElectrical = NWScript.TRAP_BASE_TYPE_EPIC_ELECTRICAL,
    EpicFire = NWScript.TRAP_BASE_TYPE_EPIC_FIRE,
    EpicFrost = NWScript.TRAP_BASE_TYPE_EPIC_FROST,
    EpicSonic = NWScript.TRAP_BASE_TYPE_EPIC_SONIC
  }
}