using NWN.Core;

namespace NWM.API.Constants
{
  public enum VoiceChatType
  {
    Attack = NWScript.VOICE_CHAT_ATTACK,
    BattleCry1 = NWScript.VOICE_CHAT_BATTLECRY1,
    BattleCry2 = NWScript.VOICE_CHAT_BATTLECRY2,
    BattleCry3 = NWScript.VOICE_CHAT_BATTLECRY3,
    HealMe = NWScript.VOICE_CHAT_HEALME,
    Help = NWScript.VOICE_CHAT_HELP,
    Enemies = NWScript.VOICE_CHAT_ENEMIES,
    Flee = NWScript.VOICE_CHAT_FLEE,
    Taunt = NWScript.VOICE_CHAT_TAUNT,
    GuardMe = NWScript.VOICE_CHAT_GUARDME,
    Hold = NWScript.VOICE_CHAT_HOLD,
    GAttack1 = NWScript.VOICE_CHAT_GATTACK1,
    GAttack2 = NWScript.VOICE_CHAT_GATTACK2,
    GAttack3 = NWScript.VOICE_CHAT_GATTACK3,
    Pain1 = NWScript.VOICE_CHAT_PAIN1,
    Pain2 = NWScript.VOICE_CHAT_PAIN2,
    Pain3 = NWScript.VOICE_CHAT_PAIN3,
    NearDeath = NWScript.VOICE_CHAT_NEARDEATH,
    Death = NWScript.VOICE_CHAT_DEATH,
    Poisoned = NWScript.VOICE_CHAT_POISONED,
    SpellFailed = NWScript.VOICE_CHAT_SPELLFAILED,
    WeaponSucks = NWScript.VOICE_CHAT_WEAPONSUCKS,
    FollowMe = NWScript.VOICE_CHAT_FOLLOWME,
    LookHere = NWScript.VOICE_CHAT_LOOKHERE,
    Group = NWScript.VOICE_CHAT_GROUP,
    MoveOver = NWScript.VOICE_CHAT_MOVEOVER,
    PickLock = NWScript.VOICE_CHAT_PICKLOCK,
    Search = NWScript.VOICE_CHAT_SEARCH,
    Hide = NWScript.VOICE_CHAT_HIDE,
    CanDo = NWScript.VOICE_CHAT_CANDO,
    CantDo = NWScript.VOICE_CHAT_CANTDO,
    TaskComplete = NWScript.VOICE_CHAT_TASKCOMPLETE,
    Encumbered = NWScript.VOICE_CHAT_ENCUMBERED,
    Selected = NWScript.VOICE_CHAT_SELECTED,
    Hello = NWScript.VOICE_CHAT_HELLO,
    Yes = NWScript.VOICE_CHAT_YES,
    No = NWScript.VOICE_CHAT_NO,
    Stop = NWScript.VOICE_CHAT_STOP,
    Rest = NWScript.VOICE_CHAT_REST,
    Bored = NWScript.VOICE_CHAT_BORED,
    Goodbye = NWScript.VOICE_CHAT_GOODBYE,
    Thanks = NWScript.VOICE_CHAT_THANKS,
    Laugh = NWScript.VOICE_CHAT_LAUGH,
    Cuss = NWScript.VOICE_CHAT_CUSS,
    Cheer = NWScript.VOICE_CHAT_CHEER,
    TalkToMe = NWScript.VOICE_CHAT_TALKTOME,
    GoodIdea = NWScript.VOICE_CHAT_GOODIDEA,
    BadIdea = NWScript.VOICE_CHAT_BADIDEA,
    Threaten = NWScript.VOICE_CHAT_THREATEN
  }
}