using NWN.Core;

namespace NWM.API.Constants
{
  public enum IPArcaneSpellFailure
  {
    Minus50Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_50_PERCENT,
    Minus45Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_45_PERCENT,
    Minus40Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_40_PERCENT,
    Minus35Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_35_PERCENT,
    Minus30Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_30_PERCENT,
    Minus25Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_25_PERCENT,
    Minus20Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_20_PERCENT,
    Minus15Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_15_PERCENT,
    Minus10Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_10_PERCENT,
    Minus5Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_MINUS_5_PERCENT,
    Plus5Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_5_PERCENT,
    Plus10Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_10_PERCENT,
    Plus15Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_15_PERCENT,
    Plus20Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_20_PERCENT,
    Plus25Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_25_PERCENT,
    Plus30Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_30_PERCENT,
    Plus35Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_35_PERCENT,
    Plus40Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_40_PERCENT,
    Plus45Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_45_PERCENT,
    Plus50Pct = NWScript.IP_CONST_ARCANE_SPELL_FAILURE_PLUS_50_PERCENT
  }
}