using NWN;

namespace NWM.API.Constants
{
  public enum IPClass
  {
    IP_CONST_CLASS_BARBARIAN = NWScript.IP_CONST_CLASS_BARBARIAN,
    IP_CONST_CLASS_BARD = NWScript.IP_CONST_CLASS_BARD,
    IP_CONST_CLASS_CLERIC = NWScript.IP_CONST_CLASS_CLERIC,
    IP_CONST_CLASS_DRUID = NWScript.IP_CONST_CLASS_DRUID,
    IP_CONST_CLASS_FIGHTER = NWScript.IP_CONST_CLASS_FIGHTER,
    IP_CONST_CLASS_MONK = NWScript.IP_CONST_CLASS_MONK,
    IP_CONST_CLASS_PALADIN = NWScript.IP_CONST_CLASS_PALADIN,
    IP_CONST_CLASS_RANGER = NWScript.IP_CONST_CLASS_RANGER,
    IP_CONST_CLASS_ROGUE = NWScript.IP_CONST_CLASS_ROGUE,
    IP_CONST_CLASS_SORCERER = NWScript.IP_CONST_CLASS_SORCERER,
    IP_CONST_CLASS_WIZARD = NWScript.IP_CONST_CLASS_WIZARD
  }
}