using NWN.Core;

namespace Anvil.API
{
  public enum IPCastSpellNumUses
  {
    SingleUse = NWScript.IP_CONST_CASTSPELL_NUMUSES_SINGLE_USE,
    ChargesPerUse5 = NWScript.IP_CONST_CASTSPELL_NUMUSES_5_CHARGES_PER_USE,
    ChargesPerUse4 = NWScript.IP_CONST_CASTSPELL_NUMUSES_4_CHARGES_PER_USE,
    ChargesPerUse3 = NWScript.IP_CONST_CASTSPELL_NUMUSES_3_CHARGES_PER_USE,
    ChargesPerUse2 = NWScript.IP_CONST_CASTSPELL_NUMUSES_2_CHARGES_PER_USE,
    ChargePerUse1 = NWScript.IP_CONST_CASTSPELL_NUMUSES_1_CHARGE_PER_USE,
    ChargesPerUse0 = NWScript.IP_CONST_CASTSPELL_NUMUSES_0_CHARGES_PER_USE,
    UsePerDay1 = NWScript.IP_CONST_CASTSPELL_NUMUSES_1_USE_PER_DAY,
    UsesPerDay2 = NWScript.IP_CONST_CASTSPELL_NUMUSES_2_USES_PER_DAY,
    UsesPerDay3 = NWScript.IP_CONST_CASTSPELL_NUMUSES_3_USES_PER_DAY,
    UsesPerDay4 = NWScript.IP_CONST_CASTSPELL_NUMUSES_4_USES_PER_DAY,
    UsesPerDay5 = NWScript.IP_CONST_CASTSPELL_NUMUSES_5_USES_PER_DAY,
    UnlimitedUse = NWScript.IP_CONST_CASTSPELL_NUMUSES_UNLIMITED_USE,
  }
}
