using NWN.Core;

namespace Anvil.API
{
  public enum IPDamageBonus
  {
    Plus1 = NWScript.IP_CONST_DAMAGEBONUS_1,
    Plus2 = NWScript.IP_CONST_DAMAGEBONUS_2,
    Plus3 = NWScript.IP_CONST_DAMAGEBONUS_3,
    Plus4 = NWScript.IP_CONST_DAMAGEBONUS_4,
    Plus5 = NWScript.IP_CONST_DAMAGEBONUS_5,
    Plus1d4 = NWScript.IP_CONST_DAMAGEBONUS_1d4,
    Plus1d6 = NWScript.IP_CONST_DAMAGEBONUS_1d6,
    Plus1d8 = NWScript.IP_CONST_DAMAGEBONUS_1d8,
    Plus1d10 = NWScript.IP_CONST_DAMAGEBONUS_1d10,
    Plus2d6 = NWScript.IP_CONST_DAMAGEBONUS_2d6,
    Plus2d8 = NWScript.IP_CONST_DAMAGEBONUS_2d8,
    Plus2d4 = NWScript.IP_CONST_DAMAGEBONUS_2d4,
    Plus2d10 = NWScript.IP_CONST_DAMAGEBONUS_2d10,
    Plus1d12 = NWScript.IP_CONST_DAMAGEBONUS_1d12,
    Plus2d12 = NWScript.IP_CONST_DAMAGEBONUS_2d12,
    Plus6 = NWScript.IP_CONST_DAMAGEBONUS_6,
    Plus7 = NWScript.IP_CONST_DAMAGEBONUS_7,
    Plus8 = NWScript.IP_CONST_DAMAGEBONUS_8,
    Plus9 = NWScript.IP_CONST_DAMAGEBONUS_9,
    Plus10 = NWScript.IP_CONST_DAMAGEBONUS_10,
  }
}
