using NWN;

namespace NWM.API.Constants
{
  public enum IPDamageSoak
  {
    HP5 = NWScript.IP_CONST_DAMAGESOAK_5_HP,
    HP10 = NWScript.IP_CONST_DAMAGESOAK_10_HP,
    HP15 = NWScript.IP_CONST_DAMAGESOAK_15_HP,
    HP20 = NWScript.IP_CONST_DAMAGESOAK_20_HP,
    HP25 = NWScript.IP_CONST_DAMAGESOAK_25_HP,
    HP30 = NWScript.IP_CONST_DAMAGESOAK_30_HP,
    HP35 = NWScript.IP_CONST_DAMAGESOAK_35_HP,
    HP40 = NWScript.IP_CONST_DAMAGESOAK_40_HP,
    HP45 = NWScript.IP_CONST_DAMAGESOAK_45_HP,
    HP50 = NWScript.IP_CONST_DAMAGESOAK_50_HP
  }
}