using NWN;

namespace NWM.API.Constants
{
  public enum IPSpellResistanceBonus
  {
    Bonus10 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_10,
    Bonus12 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_12,
    Bonus14 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_14,
    Bonus16 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_16,
    Bonus18 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_18,
    Bonus20 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_20,
    Bonus22 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_22,
    Bonus24 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_24,
    Bonus26 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_26,
    Bonus28 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_28,
    Bonus30 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_30,
    Bonus32 = NWScript.IP_CONST_SPELLRESISTANCEBONUS_32
  }
}